### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by praetorian555** [linaro-swg/optee_android_manifest#12]
Hello,

hoping you can help me with error that I'm getting when i start step 3.8. Output of the error is:

============================================
PLATFORM_VERSION_CODENAME=O
PLATFORM_VERSION=O
TARGET_PRODUCT=hikey
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a15
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-3.13.0-113-generic-x86_64-with-Ubuntu-14.04-trusty
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=NYC
OUT_DIR=out
============================================
[2/2] bootstrap out/soong/.minibootstrap/build.ninja.in
[1/1] out/soong/.bootstrap/bin/minibp out/soong/.bootstrap/build.ninja
[10/11] glob system/tools/*/Android.bp
[18/19] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja 
out/soong/.bootstrap/bin/soong_build -t -b out/soong -d out/soong/build.ninja.d -o out/soong/build.ninja Android.bp
[19/19] soong_build docs out/soong/.bootstrap/docs/soong_build.html
FAILED: out/soong/.bootstrap/docs/soong_build.html 
out/soong/.bootstrap/bin/soong_build  -t -b out/soong --docs out/soong/.bootstrap/docs/soong_build.html ./Android.bp
config file: out/soong/soong.variables did not parse correctly: invalid character 'd' after object key:value pair
ninja: build stopped: subcommand failed.
14:02:50 soong bootstrap failed with: exit status 1
make: *** [run_soong_ui] Error 1

**Comment by vchong** [comment]
Are you using the `master` branch? If so, please try the `hikey-n-4.9` branch.

**Comment by praetorian555** [comment]
Yes, I was using master branch. Tried with hikey-n-4.9 and it works. Thank you very much. I'm closing the issue.

**Comment by praetorian555** [comment]
Had a problem running tee_helloworld it throws an error with code 0xFFFF0008. So have you successfully run this test?

**Comment by vchong** [comment]
Can you try running it as root? I think maybe `xtest` now has permission to run as shell (non-root) user, but not `tee_helloworld`.

**Comment by praetorian555** [comment]
That was the problem, thanks.
