### ISSUE TITLE
How to import ta/ca 

### ISSUE THREAD

**Issue by nikoskoutr** [linaro-swg/optee_android_manifest#14]
Hello,
I want to include my TA and CA on android and run it on the hikey.
The CA also require openssl, which i have compiled for android.
Is there a guide for how to include all of the above on android? (CA, TA, openssl)
Also, is there a way to compile just my TA/CA and test it on the board without recompiling everything?

Thank you for your help,
Nick

**Comment by vchong** [comment]
You'll have to write Android makefiles for your CA and TA and compile them. E.g. for our https://github.com/linaro-swg/hello_world example, https://github.com/linaro-swg/hello_world/blob/master/Android.mk is for the CA and https://github.com/linaro-swg/hello_world/blob/master/ta/Android.mk is for the TA. The makefiles 

I'm not sure if this is required but just to be safe, put your source directory under `external/`, where the other `optee_*` source directories are. Then add the name of your CA, TA and libopenssl to `device/linaro/hikey/optee-packages.mk`. See https://android-review.linaro.org/#/c/17718/1/optee-packages.mk for reference. After that, you can build them directly. E.g. again for hello_world, we can do:

```
make TARGET_bla_bla=bla TARGET_bla_bla=bla tee_helloworld
make TARGET_bla_bla=bla TARGET_bla_bla=bla 8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta
```

**Comment by vchong** [comment]
After building, you can just `adb push` the files to the board.

**Comment by nikoskoutr** [comment]
Thank you for your help,
I followed your instructions and everything is working as expected!
