### ISSUE TITLE
A problem when running "./optee/build_kernel.sh"

### ISSUE THREAD

**Issue by wxlqaz** [linaro-swg/optee_android_manifest#16]
Hello 
Hope you can help me with error  when I start step 3.7.
I have followed the steps in ''https://github.com/linaro-swg/optee_android_manifest'' and everything works well before. However, when I running "./optee/build_kernel.sh", it has shown that:

make: Entering directory '/home/duduslave/hikey/device/linaro/hikey-kernel'
make: *** No rule to make target 'hikey_defconfig'.  Stop.
make: Leaving directory '/home/duduslave/hikey/device/linaro/hikey-kernel'
Error: Unable to configure kernel

And I find that there are no 'hikey_defconfig' file in '/home/duduslave/hikey/device/linaro/hikey-kernel' directory. Have I missed some steps? Or I have to download this file in other places?
Thank you so much!

**Comment by vchong** [comment]
The info you're using is outdated.
Please follow https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master instead.

**Comment by wxlqaz** [comment]
Thank you so much, I 'll try it~
