### ISSUE TITLE
A problem when running flash-all.sh

### ISSUE THREAD

**Issue by wxlqaz** [linaro-swg/optee_android_manifest#17]
Hello,
I have followed steps in https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master and everything works properly before step 4. However, there exists a problem when running flash-all.sh as what it said in step 4. It just shows that the "fip.bin" has flashed successfully, and the flash-all.sh script is stopped. But when I read this script, I find that it still need to use "flashboot" some "img" files such as boot.img, cache.img, nvme.img and so on, besides that, When I try to flash these .img files by myself, I find that there is no "boot.img" exist anywhere. Have I missed some steps? Or I have to download this file in other places?
Thank you so much!

**Comment by vchong** [comment]
You're right. The instruction is not complete. They will be fixed. Thanks for the report!
In the meantime, you can find the "img" files in `out/target/product/hikey`. You can copy them to where flash-all.sh is, and run flash-all.sh again, or flash these manually from `out/target/product/hikey`.

**Comment by wxlqaz** [comment]
Thanks for your help, in fact, after installing the "l-loader.bin"by flash-all.sh, I have used the ‘’fastboot” to flash these files include fip.bin, nvme.img, boot.img, etc manually, since the "fastboot" mode require the jumper link 1-2 and 5-6, and leave the 3-4 open. Finally the android system has successfully installed in hikey board. Thank you so much!
