### ISSUE TITLE
A problem when running "xtest" in hikey board

### ISSUE THREAD

**Issue by wxlqaz** [linaro-swg/optee_android_manifest#18]
Hello:
I have followed the steps in https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master and the android + optee system has installed in the hikey board. However, after flashing these .img files as step 5 and reboot the hikey board, I use the adb and try to run the "xtest" but it shows that:
root@hikey:/ # xtest                                                           
Run test suite with level=0

TEE test application started with device [(null)]
Failed to open TEE context: 0xffff0008
255|root@hikey:/ # 

And things are the same when I run the "tee_helloworld":

255|root@hikey:/ # tee_helloworld                                              
tee_helloworld: TEEC_InitializeContext failed with code 0xffff0008

So how to fix this problem? Have I missed anything?

Thank you so much!!

**Comment by vchong** [comment]
Did you also flash fip.bin?

`sudo fastboot flash fastboot fip.bin`

**Comment by wxlqaz** [comment]
Hi, 
Yes, In fact, I have followed the step 5 in https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master again, and it shows that I have successfully flashed all of the files in hikey board. but the result is still the "Failed to open TEE context: 0xffff0008"  when I run the "xtest".
Thank you.

**Comment by wxlqaz** [comment]
Hi, 
I have flashed the hikey board again and reboot the hikey board. Result is same as before. Besides, I find that when I type "ls -al /dev/tee* " in hikey board, it shows that " ls: /dev/tee*: No such file or directory ". And I can not find anything which is related to optee except the "xtest", "tee", "tee_helloworld" "tee_supplicant" exists in " system/bin " directory. So based on these appearance, will I misses something? Could you please tell me how to fix it?
Thank you so much !

**Comment by vchong** [comment]
Hi, sounds like your build wasn't complete. Let us fix the issue in https://github.com/linaro-swg/optee_android_manifest/issues/19 first and after that, you can try building again to see if the build builds to completion. I'll close this for now.
