### ISSUE TITLE
Build error hikey 8GB

### ISSUE THREAD

**Issue by pooyadav** [linaro-swg/optee_android_manifest#22]
/bin/bash -c "(xmllint device/linaro/hikey/etc/permissions/android.hardware.screen.xml >/dev/null ) && (mkdir -p out/target/product/hikey/system/etc/permissions/ ) && (out/host/linux-x86/bin/acp -fp device/linaro/hikey/etc/permissions/android.hardware.screen.xml out/target/product/hikey/system/etc/permissions/android.hardware.screen.xml )"
/bin/bash: xmllint: command not found
ninja: build stopped: subcommand failed.
build/core/ninja.mk:148: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

**Comment by vchong** [comment]
Install xmllint on your PC.

**Comment by pooyadav** [comment]
Thanks, it worked but it would be nice to add that in pre-requisite modules.

**Comment by vchong** [comment]
Added. Thanks.
