### ISSUE TITLE
SDP Support on AOSP+OPTEE+HiKey. 

### ISSUE THREAD

**Issue by pt6567** [linaro-swg/optee_android_manifest#23]
I have a couple of queries regarding SDP:

1. Is SDP working on current AOSP+OPTEE+HiKey build? In #19 , @vchong mentioned that SDP was disabled due to ion patch conflicts.
If not, is there any way to make it work using some previous release of the kernel / AOSP / OPTEE? 

3. We are using an older branch of OPTEE+AOSP [Dec 2016] for our project and moving to the latest / newer release is not feasible due to project constraints. I tried flashing the latest optee fip.bin, the system boots but even opening session for hello world TA fails. Is this the right way to do it? What other changes will be required to make it work?
Is  there a way to patch AOSP to add SDP support?

**Comment by vchong** [comment]
I just reenabled SDP so you can start again from step 3.3.

**Comment by pt6567** [comment]
@vchong  - Thank you for providing the patch. It works now.
