### ISSUE TITLE
Synchronous Exceptionion at 0x0000000037D2450C.

### ISSUE THREAD

**Issue by pt6567** [linaro-swg/optee_android_manifest#24]
With the latest fresh build, it show "**Synchronous Exceptionion at 0x0000000037D2450C**" on UART. System fails to boot.
```
Firmware
NOTICE:  BL1: v1.1(re Oct 24 2017
y:1190494208Hz

INFO:    lpddr3_freq_init, set ddrc 533mhz
INFO:    init ddr3 rank0
INFO:    ddr3 rank1 init pass
INFO:    lpddr3_freq_init, set ddr_set_freq: set acpu freq success!NOTICE:  BL2: v1.1(release):179eae6
NOTICE:  BL2: Built : 11:57:59, Oct 24 2017
NOTICE:  BL1: Booting BL3-NOTICE:  BL3-1: v1.1(release)Kernel...

onous Except at 0x000000ynchronous Eous Exception at 0x0000000037D2450C


Synchception at 0x0000000037D2450C


Synchronous Exception at 0x0000000037D2450C
```

**Comment by vchong** [comment]
I just tried 2 days ago without issues. Can you list all the steps you performed to get to this point? Usually the kernel logs don't appear so early in the boot process.

**Comment by pt6567** [comment]
I switched back to the old stable branch I had. Will reopen this issue if I face he same error again when using the latest branch.
