### ISSUE TITLE
Can I build optee + LineageOS

### ISSUE THREAD

**Issue by loganwhite** [linaro-swg/optee_android_manifest#26]
can i build the optee along with the LineageOS so that I can run it on a physical phone.

**Comment by generosocarbone** [comment]
I'm interested into this too

**Comment by vchong** [comment]
You would have to first port OP-TEE and maybe also [Arm Trusted Firmware](https://github.com/ARM-software/arm-trusted-firmware) (if Arm v8) to your platform.

**Comment by loganwhite** [comment]
Can I simply `diff` the manifest file in this [page](https://android.googlesource.com/platform/manifest/+/master/default.xml) as well as the `optee_android_manifest` and add those different projects to the LineageOS manifest file?

**Comment by vchong** [comment]
Sorry no. `optee_android_manifest` is for the HiKey reference board only, i.e. many things are HW dependent, not SW only. Boot loaders (in a sense) are HW specific and not something you just build and run anywhere.

**Comment by RoyNeverGiveUp** [comment]
I wonder if the payment software called Trusty.

**Comment by vchong** [comment]
@RoyNeverGiveUp What about Trusty? Trusty is Google's TEE OS. See https://source.android.com/security/trusty for details.

**Comment by loganwhite** [comment]
@vchong I have tried Trusty built it but this page lacks the documents on how to run it along with the Android. Do you know where can I find materials about them?

**Comment by vchong** [comment]
Trusty is Google software so please ask them instead. They might be able to provide more info.
