### ISSUE TITLE
Problem about last commit

### ISSUE THREAD

**Issue by tesmnorth** [linaro-swg/optee_android_manifest#32]
`Commit: db5e064ba43fda7b5dc80da359262874d3742cca` causes error `repo sync`. 
If you change r7 back, there is no problem.

**Comment by vchong** [comment]
It was updated to 8.1.0_r14 recently and worked for me. Did you try from the very beginning, i.e. `repo init ..`?

**Comment by vchong** [comment]
Ok. I don’t see an r14 tag for platform/frameworks/layoutlib. Will try to investigate. In the meantime, please continue to use r7 for now.

**Comment by tesmnorth** [comment]
Yes, Right now I am trying 8.1.0_r7 there is no problem. Everything in xtest is ok.
