### ISSUE TITLE
Communication error between Linux and OPTEE - memory mapping changed in kernel ?

### ISSUE THREAD

**Issue by ppeiffer-invn** [linaro-swg/optee_android_manifest#33]
Hi,

My env is Android 7.1 + OPTEE 3.0 on HiKey (based on a previous manifest version from this repo)
I use a fixed version of the bootloader components.
But I'm pointing on the branch android-hikey-linaro-4.9 for the Linux kernel which keeps moving

I noticed that a change done in Linux kernel the last 2 months broke the communication between Linux and OPTEE OS
From what I found so far, looks like there is memory mapping change somewhere... ?

Am I correct ? If yes, can someone point me to some solution to recover this or how to fix this ? (I didn't find any changes in optee-os that seems to fix this)

Thanks,

**Comment by jockebech** [comment]
Hi, you are probably right here. We haven't had any automatic CI/test for the AOSP + OP-TEE builds (something we are about to improve) and in addition to that we have no engineer available to focus on this for the moment, so currently this has been a best effort work done by @vchong . All this together unfortunately means that the OP-TEE + AOSP builds breaks from time to time. As mentioned, we want to fix this in a better way in the future, but right now we have a couple of other ares which has higher priority, so this unfortunately have to wait.

If you have time and want to contribute, then you could try syncing up things to latest in the OP-TEE gits / branches / patches that are being used in this setup and then submit updated patches for this. We would be more than happy if that would happen.

**Comment by vchong** [comment]
@ppeiffer We're aware of the issue (see https://github.com/linaro-swg/optee_android_manifest/commit/6a217280d89dc36c2f8d7740bcb27317df1da179 for temp/hack workaround) and trying to find opportunities to look into it, but it should still have been working about a month ago (the changes in Linux kernel were merged on 2/21: https://android-git.linaro.org/kernel/hikey-linaro.git/log/?h=android-hikey-linaro-4.9&qt=grep&q=TEE), so wondering why you're saying 2 months?  Do you have any other info regarding this issue? As @jbech-linaro said, we'd appreciate any help we can get right now.

Other workarounds you can try are 1. remove the tee-related kernel changes merged on 2/21, or 2. use a version of the kernel before the 2/21 changes got merged.

**Comment by ppeiffer-invn** [comment]
Thanks for that; I'm speaking about 2 months ago just because I didn't update my env in the meantime.

I'll try to have a look with the time I have.

P.

**Comment by jockebech** [comment]
That would be great @ppeiffer and would help us a lot, thanks!

**Comment by vchong** [comment]
@ppeiffer this has been fixed. Please re-open if you still have issues.
