### ISSUE TITLE
can't open bluetooth inhikey620

### ISSUE THREAD

**Issue by bryan370210** [linaro-swg/optee_android_manifest#34]
Hello，
the  hikey-n-4.9-maste is flashed into hikey 620, but the bluetooth is not able to be opened.

**Comment by jockebech** [comment]
Hi Bryan, this is unrelated to OP-TEE, or? Remember that this "optee_android_manifest" is mainly about getting OP-TEE to run on "some" Android build and we cannot guarantee that everything else used in this AOSP setup will work. In those cases it is probably better to talk to the maintainers of various components for a particular device.

**Comment by vchong** [comment]
@bryan370210 @jbech-linaro is right. If bluetooth doesn't work in `hikey-n-4.9-master`, then it most probably doesn't work in the regular/vanilla/non-OP-TEE `android-7.1.2_r33 + linaro-nougat-tv` build as well. In any case, `hikey-n-4.9-master` is outdated, obsolete and not maintained at this point, so please try `lcr-ref-hikey-o` instead.
