### ISSUE TITLE
I want to know the principle

### ISSUE THREAD

**Issue by Cukuyo** [linaro-swg/optee_android_manifest#35]
Last week, i studied OPTEE-OS . I installed it on my ubuntu16, and run hello-world. I know that it is a CPU running two OS architectures , one is OPTEE-OS, the another is Linux. So , i guess the optee_android is that Linux is replaced by Android, is it?
If it is true , please tell me the detail. 
Thanks!

**Comment by vchong** [comment]
@Cukuyo Yes, you're basically right. What other details do you need?

**Comment by Cukuyo** [comment]
@vchong There is a Linux OS in the OPTEE-OS folder. I think it is not simply that replcing the OS file. So, when i finish downloading AOSP and OPTEE-OS, what is the next step? I guess, the process is the OPTEE-OS will be compiled in the Android and be part of Android. when we launch the Android , the OPTEE-OS will be launched. 
In the process of this replacement system, there might be some configuration of parameters, such as what startup or something.

**Comment by vchong** [comment]
@Cukuyo When you run hello-world on your ubuntu16, which OP-TEE platform did you use? Qemu?

If you want to build AOSP and OPTEE-OS, just follow the instructions on https://github.com/linaro-swg/optee_android_manifest/tree/lcr-ref-hikey-o, but this is for HiKey board only.

**Comment by Cukuyo** [comment]
@vchong Yes, Qemu. So, if i want to use Qemu platform, or other platform except HiKey, what should i to do? Please tell me.
Very thanks.

**Comment by vchong** [comment]
@Cukuyo AOSP and OPTEE-OS build isn't available in Qemu. I'm not even sure if AOSP build alone is available in Qemu yet or not. For real hardware, other than HiKey, there's TI board (https://github.com/petegriffin/misc-docs/blob/master/am57xx-android.md), but not sure how easy it is to get. There's also Poplar board but it's work in progress so no build instructions yet.

**Comment by Cukuyo** [comment]
@vchong Thanks for your help
