### ISSUE TITLE
Can only handle FAT with 1 reserved sector

### ISSUE THREAD

**Issue by bryan370210** [linaro-swg/optee_android_manifest#36]
hello,
I try to build  lc-ref-hikey-o, and get this error:

mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
mkfs.fat 4.0 (2016-05-06)
Traceback (most recent call last):
  File "build/tools/fat16copy.py", line 773, in <module>
    root = fat(sys.argv[1]).root
  File "build/tools/fat16copy.py", line 469, in __init__
    "Can only handle FAT with 1 reserved sector"
AssertionError: Can only handle FAT with 1 reserved sector
[ 99% 84368/84549] //frameworks/rs:lib...-linker libRS_internal.so.lsdump [arm]
ninja: build stopped: subcommand failed.
02:57:22 ninja failed with: exit status 1

**Comment by vchong** [comment]
I've been building ok since last week. Did you make any changes? Did you try building from scratch?

**Comment by jockebech** [comment]
For other people getting this error message I'm adding a note here. It seems like using a too new version of mkfs.fat (mkfs.vfat) will trigger this error. With an older version things are OK.

* mkfs.fat 3.0.28 --> OK
* mkfs.fat 4.1 --> the error above.

You can find the `3.0.28` version [here](https://github.com/dosfstools/dosfstools/releases/tag/v3.0.28). With that you can just compile it (by running make), then all you have to do is to ensure that this version is in your `PATH` before the distros version. I.e., typically you do:
```bash
$ export PATH=/path/to/my/local/dosfstools:$PATH
```

**Comment by yang-neu** [comment]
Another simple approach.

https://github.com/brobwind/pie-device-brobwind-rpi3/issues/4

Excerpt:

sudo apt remove dosfstools
git clone https://github.com/dosfstools/dosfstools.git 
cd dosfstools/
git checkout v3.0.28
make
sudo apt install checkinstall
sudo checkinstall
