### ISSUE TITLE
can't flash hikey-n-49-master into hikey620

### ISSUE THREAD

**Issue by bryan370210** [linaro-swg/optee_android_manifest#37]
hl, my board is hikey 620, and I have been building and flashing  hikey-n-49-master succesfufly many time, but recently I get something wrong: 
The build envirentment has not changed, newly downloadling and buildking  hikey-n-49-master is all right. when run "./device/linaro/hikey/installer/hikey/flash-all.sh /dev/ttyUSB0", it can not work.  I try to find the reason and find that after flash l-loader.bin, fastboot devices can't list the device, and the flash progress stop to wait.

I have tried many times in diffrent computer, then get the same result.

**Comment by vchong** [comment]
@bryan370210 N build is not supported anymore. It seems that you're already trying O build in other issues that you'd opened, so can this be closed?
