### ISSUE TITLE
where is the file 'optee-packages.mk' in lcr-ref-hikey-o ?

### ISSUE THREAD

**Issue by bryan370210** [linaro-swg/optee_android_manifest#38]
Hi, I used steps 3.2b-3.3b in https://github.com/linaro-swg/optee_android_manifest ,and the AOSP can be builded successful . But I can't find the file 'device/linaro/hikey/optee-packages.mk' in this version.

**Comment by vchong** [comment]
3.2b-3.3b is the same as the original build before `relatively stable` builds, i.e. 3.2a-3.3b were introduced, so not sure how `optee-packages.mk` can go missing, unless you forgot to apply the patches, i.e. step 3.4?
