### ISSUE TITLE
xtest error

### ISSUE THREAD

**Issue by bryan370210** [linaro-swg/optee_android_manifest#39]
Hi，I tried lcr-ref-hikey-o with pinned-manifest_20180406.xml， use steps 3.2a-3.3a，after flash the board , when run xtest, get these errors:

hikey:/system/bin # xtest
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# regression
#
######################################################

* regression_1001 Core self tests
external/optee_test/host/xtest/regression_1000.c:294: res has an unexpected value: 0xffff000e = TEEC_ERROR_COMMUNICATION, expected 0x0 = TEEC_SUCCESS
Segmentation fault

**Comment by vchong** [comment]
Sorry, there was a bug in the `optee_os` snapshot of this manifest.
Try below. No need to re-sync the repos.

```
rm -f out/dist/fip.bin
cd optee/optee_os
git fetch github master && git checkout FETCH_HEAD
cd ../../
make TARGET_BUILD_KERNEL=true TARGET_BOOTIMAGE_USE_FAT=true \
CFG_SECURE_DATA_PATH=y CFG_SECSTOR_TA_MGMT_PTA=y TARGET_TEE_IS_OPTEE=true \
TARGET_BUILD_UEFI=true 
```

After rebuild, just re-flash `fip.bin`, i.e. `fastboot flash fastboot out/dist/fip.bin`.

**Comment by bryan370210** [comment]
@vchong 
tried the above steps, but build failed

[ 10% 9079/84596] target thumb C: libp...al/piglit/tests/util/piglit-dispatch.c
In file included from external/piglit/tests/util/piglit-dispatch.c:28:
external/piglit/tests/util/piglit-util-waffle.h:92:51: warning: unused parameter 'shared_ctx' [-Wunused-parameter]
                           struct waffle_context *shared_ctx)
                                                  ^
external/piglit/tests/util/piglit-dispatch.c:97:41: warning: unused parameter 'gl_10x_version' [-Wunused-parameter]
get_wfl_core_proc(const char *name, int gl_10x_version)
                                        ^
2 warnings generated.
ninja: build stopped: subcommand failed.
17:32:58 ninja failed with: exit status 1

**Comment by vchong** [comment]
@bryan370210 there are no errors in your log. Please copy and paste the full build log onto a paste bin somewhere and share the url.

**Comment by bryan370210** [comment]
@vchong 
the build log file is here:
https://github.com/bryan370210/buildlog

**Comment by vchong** [comment]
@bryan370210 ok, i think there are some old build artifacts interfering with the rebuild. Do you mind starting from scratch please? It'll be easier. I'd also 'fixed' `pinned-manifest_20180406.xml` so make sure you have download it again.

**Comment by bryan370210** [comment]
o regression_1013.2.22 SHA-256 loop repeat 1000
  regression_1013.2.22 OK
o regression_1013.2.23 Busy loop repeat 10000
  regression_1013.2.23 OK
o regression_1013.2.24 SHA-256 loop repeat 1000
  regression_1013.2.24 OK
    Number of parallel threads: 3
    Mean concurrency: 2.95833
  regression_1013.2 OK
  regression_1013 OK

* regression_1014 Test secure data path against SDP TAs and pTAs
o regression_1014.1 SDP: NonSecure client invokes a SDP TA
Info: can't query heaps data, try old API

**after this, the board will reboot**

**Comment by vchong** [comment]
On your board, is there a `0d4904c7-b9ee-4508-a407-e24046833ec1.ta` file in `system/lib/optee_armtz`?

**Comment by bryan370210** [comment]
no this file

**Comment by vchong** [comment]
> no this file

Then something is wrong with the build.

**Comment by vchong** [comment]
Try
```
make TARGET_BUILD_KERNEL=true TARGET_BOOTIMAGE_USE_FAT=true \
CFG_SECURE_DATA_PATH=y CFG_SECSTOR_TA_MGMT_PTA=y TARGET_TEE_IS_OPTEE=true \
TARGET_BUILD_UEFI=true 0d4904c7-b9ee-4508-a407-e24046833ec1.ta
```
and see if you get any errors. If not, then `adb push` this file to your board.

**Comment by bryan370210** [comment]
[ 50% 1/2] glob vendor/*/*/Android.bp
ninja: error: unknown target '0d4904c7-b9ee-4508-a407-e24046833ec1.ta'
08:50:12 ninja failed with: exit status 1

**Comment by bryan370210** [comment]
@vchong 

[ 50% 1/2] glob vendor/*/*/Android.bp
ninja: error: unknown target '0d4904c7-b9ee-4508-a407-e24046833ec1.ta'
08:50:12 ninja failed with: exit status 1

**Comment by vchong** [comment]
Sorry, I copied the wrong uuid. Let's start again.

On your board, is there a `12345678-5b69-11e4-9dbb-101f74f00099.ta` file in `system/lib/optee_armtz`?

**Comment by bryan370210** [comment]
@vchong 
  yes，that file exist

**Comment by vchong** [comment]
Sorry but it's hard to tell what's wrong from here at this point. Were you able to apply the patches (step 3.4) without issues when using the pinned manifest? Perhaps you can try 3.2b-3.3b instead?
