### ISSUE TITLE
can not build  so in 64 bit

### ISSUE THREAD

**Issue by bryan370210** [linaro-swg/optee_android_manifest#40]
the  envirentment is  lc-ref-hikey-o 

    source ./build/envsetup.sh
    lunch hikey-userdebug
    make TARGET_BUILD_KERNEL=true TARGET_BOOTIMAGE_USE_FAT=true CFG_SECURE_DATA_PATH=y CFG_SECSTOR_TA_MGMT_PTA=y TARGET_TEE_IS_OPTEE=true TARGET_BUILD_UEFI=true xxx

I use these command to build  xxx executable file   or  xxx.so ,  the buiding of execcutable  is ok ,  after I modified the Android.mk file to build so , the build is ok ,  but the result xxx.so is in 32 bit , not in 64 bit.

In 4.9 has not  this problem.

**Comment by vchong** [comment]
64 bit so is in system/lib64. Did you look there?

What's 4.9?

**Comment by bryan370210** [comment]
@vchong  the older version of hikey-n-4.9-master

**Comment by vchong** [comment]
Should be the same. You're saying you can find your so in system/lib but not system/lib64?

**Comment by bryan370210** [comment]
@vchong 
my negligence, thank you

**Comment by vchong** [comment]
np.. closing..
