### ISSUE TITLE
Right branch to use with HiKey960

### ISSUE THREAD

**Issue by elkoniu** [linaro-swg/optee_android_manifest#42]
Hi all,
What branch I should use for HiKey960? lcr-ref-hikey?
If yes then I expect that for flashing I should use binaries from **hikey960** directories rather than **hikey** ?
``cp -a out/target/product/hikey960/*.img device/linaro/hikey/installer/hikey960/``
``sudo` ./device/linaro/hikey/installer/hikey960/flash-all.sh /dev/ttyUSBn``

**Comment by vchong** [comment]
There are no branches for hikey960. It's not supported atm.

**Comment by elkoniu** [comment]
It is not supported by optee_android_manifest tools or not supported by AOSP + OP-TEE on it?

**Comment by vchong** [comment]
Not supported by optee_android_manifest. There is AOSP build for HiKey960 upstream, but it is without OP-TEE. There is no support for AOSP + OP-TEE for HiKey960 atm.

**Comment by elkoniu** [comment]
Are you sure abot that? Because HiKey960 is supported by both OP-TEE and AOSP upstream separated. Then why is not supported by them combined together? It is not just the matter of putting right partitions on device and flash with images combined from upstream OP-TEE for HiKey960 and AOSP for HiKey960?

**Comment by vchong** [comment]
Yes I'm sure. The job of 'combining them together' is not so straightforward. There are many parts that need to be integrated separately. You can get an idea of what it takes to do that for the hikey620 here[1]. It's not done yet for the hikey960, and no plans to do that atm due to lack of resources.

[1] https://www.slideshare.net/linaroorg/hkg18119-overview-of-integrating-optee-into-hikey620-aosp

**Edit:** Please note that the slides might already be somewhat outdated!

**Comment by elkoniu** [comment]
I see now what the problem is.
Let me ask then my final two questions:
1) If it is possible to use builds from HiKey on HiKey960? Or the difference between them is too big?
2) If not HiKey960, then what is the "freshest" development device for OP-TEE + AOSP? Raspberry Pi 3 maybe (it is also on OP-TEE support list)?

**Comment by vchong** [comment]
1. We tried to do it here (https://discuss.96boards.org/t/optee-android-in-hikey960), but it's too complicated and ugly and hard to use and error prone and many other negatives.

2. Being on the OP-TEE support list doesn't mean there's an AOSP + OP-TEE build. The best support for AOSP + OP-TEE right now is probably hikey620.

**Comment by elkoniu** [comment]
@vchong Thanks for answers and suggestion which board use.
I found a post where it looks like someone managed to put some things together and make it working: https://discuss.96boards.org/t/remote-no-such-partition-after-flashing/4120

**Comment by vchong** [comment]
You're welcome, but not sure what you mean. The post you found is just regular hikey960 aosp without op-tee as far as i can tell.

**Comment by elkoniu** [comment]
True, my mistake. One more time thank you for help! :)

**Comment by vchong** [comment]
One of our community users, @bensup, has kindly shared his implementations here: https://github.com/bsupiot/hikey960-aosp-optee/wiki. For those who are interested, please give it a try. There are some known issues so please contribute back patches if possible. A big thank you to @bensup! Thanks!

**Comment by vchong** [comment]
@elkoniu You can try hikey960 build on https://github.com/linaro-swg/optee_android_manifest now.
