### ISSUE TITLE
Unable to initialize Android correctly

### ISSUE THREAD

**Issue by NeatMonster** [linaro-swg/optee_android_manifest#43]
Hello there,

I have followed the instructions from https://github.com/linaro-swg/optee_android_manifest/blob/lcr-ref-hikey/archive/README_20180608.md, but it appears that Android is still unable to initialize properly.

Here is the output of `dmesg` on my board (Hikey620): https://pastebin.com/gFSgZ3R7.

Did I miss something? Thanks a lot for your help!

**Edit:** Forgot to mention that I used [pinned-manifest_20180520-0000.xml](https://github.com/linaro-swg/optee_android_manifest/blob/lcr-ref-hikey/archive/pinned-manifest_20180520-0000.xml). I will try using the `sync-master.sh` / `build-master.sh` as `sync-o.sh` / `build-o.sh` appear to be broken on my end.

**Comment by vchong** [comment]
The `master` build+script is probably not stable yet. The `Oreo` build+script might currently have a bug. We need some time to investigate both. How is `Oreo` broken on your end. Do you have logs?

**Comment by vchong** [comment]
Also, can you please explain 'Unable to initialize correctly'? I see that you got to a prompt. Were you able to run `xtest`?

**Comment by NeatMonster** [comment]
I could build all the `*.img` files successfully using the `master` build+script, as well as flash them on my device (HiKey620). But I think the real issue isn't within the building process.

I am able to get an ADB shell on the device. But it looks like some internal Android components fail to initialize properly. Please find below all the lines highlighted in red from the `dmesg` output.

```
[    1.661996] dmi: Firmware registration failed.
[    1.965868] hi6220-irq-debug f7113000.fiq-debugger: No signal IRQ, error=-6
[    1.965881] hi6220-irq-debug f7113000.fiq-debugger: No wakeup IRQ, error=-6
[    5.434936] hdmi-audio-codec hdmi-audio-codec.4.auto: ASoC: no source widget found for Playback
[    5.443759] hdmi-audio-codec hdmi-audio-codec.4.auto: ASoC: Failed to add route Playback -> direct -> TX
[    6.946760] watchdogd: Failed to open /dev/watchdog: No such file or directory
[    7.079325] F2FS-fs (mmcblk0p10): Can't find valid F2FS filesystem in 1th superblock
[    7.079608] F2FS-fs (mmcblk0p10): Can't find valid F2FS filesystem in 2th superblock
[    7.079634] F2FS-fs (mmcblk0p10): Can't find valid F2FS filesystem in 1th superblock
[    7.079643] F2FS-fs (mmcblk0p10): Can't find valid F2FS filesystem in 2th superblock
[    7.100310] F2FS-fs (mmcblk0p10): Can't find valid F2FS filesystem in 1th superblock
[    7.108977] init: [libfs_mgr]mount_with_alternatives(): Mounted /dev/block/platform/soc/f723d000.dwmmc0/by-name/userdata on /data with fs_type=ext4 instead of f2fs
[    7.116663] init: /recovery not specified in fstab
[    7.522065] ueventd: firmware: could not find firmware for ti-connectivity/wl1271-nvs.bin
[    7.798059] init: setpgid failed for console: Operation not permitted
[    7.800788] init: Could not start service 'flash_recovery' as part of class 'main': Cannot find '/system/bin/install-recovery.sh': No such file or directory
[    7.804449] init: couldn't write 1891 to /dev/cpuset/camera-daemon/tasks: No such file or directory
[    9.518267] init: Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start
[    9.546050] init: Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start
[   12.521024] audit: rate limit exceeded
[   12.806496] init: couldn't write 2029 to /dev/cpuset/camera-daemon/tasks: No such file or directory
[   13.381222] init: Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start
[   13.408010] init: Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start
```

I am not very familiar with the Android internals, but to me it looks a bit like the issue I have encountered with the Hikey960: https://discuss.96boards.org/t/filesystem-not-available/4938/ as a lot of `open()` calls seem to fail. But this isn't the same board and the flash appears to be from Samsung so I don't know.

I also tried running `xtest`, but I am not getting any output and the binary is returning silently after a few minutes.

Thanks for your help @vchong!

**Comment by NeatMonster** [comment]
Here is the log from the UART: https://pastebin.com/aTJjX3gW.

Here is the one from the master build: https://pastebin.com/8xmJhReN.

Here is the log when I try to boot OP-TEE alone:

```
INFO:    BL1: 0xf9810000 - 0xf9815000 [size = 20480]
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v1.4(debug):8608ac5
NOTICE:  BL1: Built : 16:34:46, Aug  3 2018
INFO:    BL1: RAM 0xf9810000 - 0xf9815000
WARNING: BL1: cortex_a53: errata workaround for 835769 was missing!
INFO:    BL1: cortex_a53: errata workaround for disable_non_temporal_hint was applied
INFO:    BL1: cortex_a53: errata workaround for 843419 was applied
INFO:    BL1: cortex_a53: errata workaround for 855873 was applied
INFO:    BL1: Loading BL2
ASSERT: plat/hisilicon/hikey/hikey_io_storage.c:204
```

**Comment by vchong** [comment]
> I could build all the *.img files successfully using the master build+script, as well as flash them on my device (HiKey620).

As mentioned above, we're in the middle of verifying some stuffs in both O and master builds due to recent Treble related changes, so you're using these with a bit of risk.

> Please find below all the lines highlighted in red from the dmesg output.

Don't see anything in red.

> I am not very familiar with the Android internals, but to me it looks a bit like the issue I have encountered with the Hikey960

The internals are very complicated so we don't know everything either but regardless of that, this purpose of this repo is only to add OP-TEE related components onto AOSP and make sure xtest is running, so that users can have an OP-TEE development platform on AOSP. If there are other non-OP-TEE related errors/issues, then those should be taken up upstream or somewhere else more relevant. If the issue looks related to the one on Hikey960, then it's probably not OP-TEE related.

> I also tried running xtest, but I am not getting any output and the binary is returning silently after a few minutes.

No logs at all? What's the output of `dmesg | grep tee` and `ps -ef | grep tee-supplicant`? Is `xtest` failing for both O and master?

> [   11.617902] Unable to handle kernel NULL pointer dereference at virtual address 00000009

Did you make any changes of your own, especially to the kernel?

> Here is the log when I try to boot OP-TEE alone:

Sorry but I don't understand. What do you mean by 'boot OP-TEE alone'? Boot it up in recovery mode?

I'd suggest waiting a bit for us to verify both the O and master builds before you continue.

**Comment by NeatMonster** [comment]
> As mentioned above, we're in the middle of verifying some stuffs in both O and master builds due to recent Treble related changes, so you're using these with a bit of risk.

I understand, that's why I tried the pinned manifest builds first, then the master build.

> Don't see anything in red.

I mean that I reported below the lines that appeared in red in the `dmesg` output. I hoped those would be more relevant and highlight the underlying issue, but I still included a link to the complete output.

> If the issue looks related to the one on Hikey960, then it's probably not OP-TEE related.

Understood. I will try a regular AOSP build to confirm or infirm that this issue is related to OP-TEE.

> No logs at all? What's the output of dmesg | grep tee and ps -ef | grep tee-supplicant? Is xtest failing for both O and master?

I'm unable to run `xtest` on the O build as the kernel panics after 10 seconds. But with the master build, nothing is printed on the standard output, but there is plenty of debug messages in the UART log (see https://dl.neat.sh/uart.log). It appears that the TA crashes multiple times.

Below is the output of the commands you requested:
```
hikey:/ # dmesg | grep tee
hikey:/ # ps -ef | grep tee-supplicant
root          1926     1 1 00:00:13 ?     00:00:02 tee-supplicant
root          5228  5040 3 00:03:48 pts/0 00:00:00 grep tee-supplicant
```

> Did you make any changes of your own, especially to the kernel?

Negative, I only ran the build and flash scripts, then booted the board.

> Sorry but I don't understand. What do you mean by 'boot OP-TEE alone'?

I mean running OP-TEE without AOSP, according to the instructions located here: https://github.com/OP-TEE/build/blob/master/README.md.

**Comment by NeatMonster** [comment]
@vchong Were you able to verify the O and master builds? I have also opened [an issue](https://github.com/OP-TEE/optee_os/issues/2499) on the OP-TEE repository because I don't think it is normal not to be able to boot OP-TEE alone.

**Comment by vchong** [comment]
I think you're mixing images from `build.git` and here. It might be better to just stick to images built from this repo. Please start from scratch, and can you please try `sync-p.sh` and `build-p.sh` if you don't mind? Then try flashing using/referencing the script in `device/linaro/hikey/installer/hikey/flash-all.sh`.

**Comment by NeatMonster** [comment]
I'm getting the following issue:
```
=== Applying 18405/1 ===
From git://android-review.linaro.org/kernel/hikey-linaro
 * branch                      refs/changes/05/18405/1 -> FETCH_HEAD
[detached HEAD 700fdbe3edc1] staging:ion: add a no-map property to ion dmabuf attachment                              Author: Etienne Carriere <etienne.carriere@linaro.org>
 Date: Mon Oct 9 13:47:40 2017 +0200
 1 file changed, 12 insertions(+)
=== AM Applying patch https://github.com/linaro-swg/linux/commit/3ed4ce4c37ef0800b5da18893212e6769e1dbd3e.patch ===
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   916    0   916    0     0   1551      0 --:--:-- --:--:-- --:--:--  1549
Applying: tee: optee: log message if dynamic shm is enabled
=== AM Applying patch https://github.com/linaro-swg/linux/commit/94c2f2e1cb08073cd688bd51638920b1cc6ad166.patch ===
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1556    0  1556    0     0   3362      0 --:--:-- --:--:-- --:--:--  3360
Applying: tee: fix unbalanced context refcount in register shm from fd


applying patchset: optee-master-workarounds
=== AM Applying patch https://github.com/liuyq/optee_client/commit/c2d9153e51a519b6f85ccbe02f4ac6abff0a45bd.patch ===
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2753    0  2753    0     0   7001      0 --:--:-- --:--:-- --:--:--  7005
error: patch failed: Makefile:29
error: Makefile: patch does not apply
error: patch failed: config.mk:3
error: config.mk: patch does not apply
Applying: Makefile and config.mk: remove export in config.mk
Patch failed at 0001 Makefile and config.mk: remove export in config.mk
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Failed to apply patch https://github.com/liuyq/optee_client/commit/c2d9153e51a519b6f85ccbe02f4ac6abff0a45bd.patch for project
HEAD is now at 18c156d Makefile and config.mk: remove export in config.mk

```

after running the following commands:
```
git clone https://github.com/linaro-swg/optee_android_manifest -b lcr-ref-hikey
cd optee_android_manifest
./sync-p.sh
```

**Comment by vchong** [comment]
Something's not right somewhere. `optee-master-workarounds` is supposed to be 'empty', i.e. no patches. See [1].

[1] https://android-git.linaro.org/android-patchsets.git/tree/optee-master-workarounds

**Comment by vchong** [comment]
Oops, sorry. It's not empty. Lemme send in a patch to fix that.

**Comment by vchong** [comment]
@NeatMonster The person in charge is on holiday this week so it might take a little while to get this resolved.

In the meantime, you can remove line 133 (`func_apply_patch optee-master-workarounds`, https://github.com/linaro-swg/optee_android_manifest/blob/lcr-ref-hikey/sync.sh#L133) in `sync.sh`, and try running `sync-p.sh` again.

However, there shouldn't be any error applying this patch. Is your `optee_client` repo clean? Maybe try deleting `optee_client` and sync again, without removing line 133 first.

**Comment by vchong** [comment]
@NeatMonster sorry, my bad. Based on your log, I found a bug in the script after all. Please try again as you did earlier, i.e. with:

```
git clone https://github.com/linaro-swg/optee_android_manifest -b lcr-ref-hikey
cd optee_android_manifest
./sync-p.sh
```
