### ISSUE TITLE
About building pinned-manifest-stable_kmgk_3.3.0.xml for Hikey960

### ISSUE THREAD

**Issue by ggulgun** [linaro-swg/optee_android_manifest#46]
Hello , 

I am trying to build optee_android_manifest 3.3.0 for hikey 960. Firstly, I cloned this repository (https://github.com/linaro-swg/optee_android_manifest.git).
After that I am trying to run this command (./sync.sh -v p -t hikey960 -bm pinned-manifest-stable_kmgk_3.3.0.xml 2>&1 |tee logs/sync-p.log) it freeze without any error. How can I fix this issue?

**Comment by vchong** [comment]
`pinned-manifest-stable_kmgk_3.3.0.xml` is a hikey (620)-only manifest. It will not work for hikey960 since it doesn't contain all the required repo! The only manifest for hikey960 right now is `pinned-manifest-stable_hikey960_initial_release_20181117.xml`. Probably we don't have a good naming system right now, but if 'hikey960' is not in the filename, then it's for hikey (620) only.

**Comment by ggulgun** [comment]
Thank you so much. Can suggest us release version for Hikey960 which is supporting integration of keystore and op-tee?

**Comment by vchong** [comment]
You're welcome. There's no release planned for hikey960 atm. Initial support for it was available only like ~2 days ago. :s We're working on keystore support right now (among other things) and will try to upload a manifest that includes it asap.

**Comment by vchong** [comment]
@pwnageco 2 hikey960 manifest that supports keystore were just merged. Please try and see how it goes.

```
pinned-manifest-stable_hikey960_initial_release_v9r10_20181121.xml
pinned-manifest-stable_hikey960_initial_release_v9r18_20181123.xml 
```

**Comment by ggulgun** [comment]
Hi again ,

 Firstly, I cloned this repository (https://github.com/linaro-swg/optee_android_manifest.git).
Then, I am trying to run this command (./sync.sh -v p -t hikey960 -bm pinned-manifest-stable_hikey960_initial_release_v9r18_20181123.xml 2>&1 |tee logs/sync-p.log). 
when run command, get these errors:

error: Exited sync due to fetch errors
Fetching project platform/test/vti/alert
Fetching project device/generic/qemu
Fetching project platform/packages/providers/TelephonyProvider

**Comment by vchong** [comment]
@pwnageco Are you still having the above issue? If yes, can you please attach `logs/sync-p.log` or paste it somewhere?

**Comment by ggulgun** [comment]
Hello ,

I am still having this issue. Log is attached.

Sincerely , 

[sync-p.log](https://github.com/linaro-swg/optee_android_manifest/files/2642711/sync-p.log)

**Comment by vchong** [comment]
Can you try below?

```
rm -f external/optee_test .repo/projects/external/optee_test.git .repo/project-objects/OP-TEE/optee_test.git
./sync.sh -v p -t hikey960 -bm pinned-manifest-stable_hikey960_initial_release_v9r18_20181123.xml 2>&1 |tee logs/sync-p.log
```

**Comment by ggulgun** [comment]
I just ran these commands.

rm -rf .repo/project-objects/OP-TEE/optee_test.git/
rm -rf .repo/projects/external/optee_test.git/

Still getting errors. 

Fetching project OP-TEE/optee_test
Fetching project platform/prebuilts/ktlint
Fetching project platform/external/jsr305
Fetching project platform/external/abiFrom https://android.googlesource.com/platform/hardware/google/easel
 * branch            0824db9ef0067d85ba76ec088c6c3b175ccaf0ef -> FETCH_HEAD
error: Server does not allow request for unadvertised object 2ad190fe81058d44adf28d2074bd14f4e590db22
error: Cannot fetch OP-TEE/optee_test
From https://android.googlesource.com/platform/packages/providers/BlockedNumberProvider
 * branch            c7951ca076f6cd3af166ff8cedc22df60c71d4ce -> FETCH_HEAD
From https://android.googlesource.com/platform/external/mksh
 * branch            1a0c2aa6bbaa9b709a2af4d560c66789686d7805 -> FETCH_HEAD
From https://android.googlesource.com/platform/hardware/qcom/bt
 * branch            683058f4e9122caa76a9a74c18f1343921143a71 -> FETCH_HEAD
From https://android.googlesource.com/platform/external/libavc
 * branch            8d910d5771a868640190647eb30f06fb5c9faee1 -> FETCH_HEAD

error: Exited sync due to fetch errors
-compliance-checker
Fetching project platform/hardware/qcom/msm8x84
Fetching project platform/external/ksoap2
Fetching project platform/external/mksh
Fetching project platform/hardware/google/easel
Fetching project platform/packages/providers/BlockedNumberProvider
Fetching project platform/external/libavc
Fetching project platform/hardware/qcom/bt

**Comment by vchong** [comment]
Hrm, not sure if the sync depth is too shallow and causing issues. In `https://github.com/linaro-swg/optee_android_manifest/blob/lcr-ref-hikey/scripts-common/sync-common.sh#L19`, can you remove `--depth=1` and try again?

**Comment by ggulgun** [comment]
I just deleted _--depth=1_ from "**repo init -u ${MIRROR} -b ${MANIFEST_BRANCH} --no-repo-verify --repo-url=${repo_url} -g ${REPO_GROUPS} -p linux**" command in /scripts-common/sync-common.sh. Still getting errors.

**Comment by vchong** [comment]
Ok. Let us look into this and get back to you. Sorry for the trouble.

**Comment by vchong** [comment]
@pwnageco Please delete your working dir and try again from scratch from the very beginning.

**Comment by ggulgun** [comment]
Thank you so much. I have one extra question. Sorry for bother.
After running ./build-p-hikey960.sh
I got some errors

[59/77] compile out/soong/.bootstrap/hidl-soong-rules/pkg/android/soong/hidl.a
[60/77] compile out/soong/.bootstrap/soong-fluoride/pkg/android/soong/fluoride.a
[61/77] compile out/soong/.bootstrap/soong-clang-prebuilts/pkg/android/soong/prebuilts/clang/host/linux-x86/clangprebuilts.a
[62/77] compile out/soong/.bootstrap/soong-clang/pkg/android/soong/external/clang.a
[63/77] compile out/soong/.bootstrap/soong-llvm/pkg/android/soong/external/llvm.a
[64/77] compile out/soong/.bootstrap/soong-phony/pkg/android/soong/phony.a
[65/77] compile out/soong/.bootstrap/soong-vts-spec/pkg/android/soong/vts/hal2vts.a
[66/77] compile out/soong/.bootstrap/soong-python/test/android/soong/python.a
[67/77] compile out/soong/.bootstrap/soong-python/pkg/android/soong/python.a
[68/77] compile out/soong/.bootstrap/soong-python/test/test.a
[69/77] compile out/soong/.bootstrap/soong-wayland-protocol-codegen/pkg/android/soong/external/wayland-protocol.a
[70/77] link out/soong/.bootstrap/soong-cc/test/test
[71/77] compile out/soong/.bootstrap/soong_build/obj/soong_build.a
[72/77] link out/soong/.bootstrap/soong-python/test/test
[73/77] test android/soong/python
[74/77] link out/soong/.bootstrap/soong_build/obj/a.out
[75/77] test android/soong/cc
[76/77] cp out/soong/.bootstrap/bin/soong_build
[77/77] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja 
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -o out/soong/build.ninja Android.bp
error: external/libdrm/Android.bp:51:23: unrecognized property "recovery_available"
ninja: build stopped: subcommand failed.
13:00:08 soong bootstrap failed with: exit status 1

real	0m30,198s
user	0m35,392s
sys	0m3,356s
Build done!
Please make sure there are no errors before flashing!

Do you have any idea?

**Comment by vchong** [comment]
You're welcome! No bother.

The patches never got applied. It's my fault, so I should be sorry! :(
Please try again. In the `optee_android_manifest` dir, run:

```
git pull
rm -rf .repo
# NOTE the xml filename change below, i.e. "_stable" has been removed!
./sync.sh -v p -t hikey960 -bm pinned-manifest_hikey960_initial_release_v9r18_20181123.xml 2>&1 |tee logs/sync-p.log
./build-p-hikey960.sh
```

Hopefully the above commands can save you some time not having to download the repos again. If there are errors, please try again from scratch from the very beginning.

**Comment by ggulgun** [comment]
Hello there , 

Thank you so much. Finally I built and deployed image into Hikey960. I have one problem. Boot is completed successfully by board. But monitor stucks on black screen after boot completed. Already I looked uart logs. Android is successfully running. Do you have any idea?


Solved Problem was in HDMI - VGA converter.
