### ISSUE TITLE
Can we use a lower version android rather than Android 9?

### ISSUE THREAD

**Issue by BeitongT** [linaro-swg/optee_android_manifest#47]
Hi, everyone. I am using the current version on my project. But it seems the Android 9 is not compatible with my GPS module. So, I am wondering can we use a lower version Android? Is it simply change the manifest? Or all the patches in this repo are related to the fix Android version? Any idea? Thanks !

**Comment by vchong** [comment]
@BeitongT For hikey620 O/v8 build is still available although we haven't tested it for a while. For hikey960, P/v9 is the only available build right now, and it doesn't look like we'll be adding support for O/v8. It's not just a simple change to the manifest. The patches are version specific, so they won't apply cleanly on O/v8. Sorry. :(

**Comment by BeitongT** [comment]
Thanks for your reply. I have figured out how to use USB GPS on hikey960. Though I have to make some changes manually every time I flash new image. But it works now! Thanks !
