### ISSUE TITLE
Applying patchsets is failing for Hikey 960

### ISSUE THREAD

**Issue by warraagal** [linaro-swg/optee_android_manifest#49]
I am trying to build for Hikey 960. I checked out the branch lcr-ref-hikey. I ran the following command:
`./sync.sh -v p -t hikey960 -u /home/rounaka/aospmirror/platform/manifest.git -j 1 2>&1 | tee logs/sync-p.log`
Syncing completed without any errors, but when it started applying patches, there was a failure when trying to apply the patch **P-RLCR-PATCHSET**, I got an error :
applying patchset: get-hikey960-gcc
Downloading gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf ...
Downloading gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu ...

applying patchset: P-RLCR-PATCHSET
=== Applying 17696/1 ===
From git://android-review.linaro.org/platform/frameworks/base
 * branch                    refs/changes/96/17696/1 -> FETCH_HEAD
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 11389 and retry the command.
[detached HEAD e4cf3e292f7] Workaround for wallpaper not shown correctly problem
 Author: Yongqin Liu <yongqin.liu@linaro.org>
 Date: Thu May 11 23:56:54 2017 +0800
 1 file changed, 5 insertions(+), 4 deletions(-)
=== Applying 18203/1 ===
From git://android-review.linaro.org/platform/system/core
 * branch                refs/changes/03/18203/1 -> FETCH_HEAD
[detached HEAD 4be4505b2] add bootchart_parse command
 Author: Yongqin Liu <yongqin.liu@linaro.org>
 Date: Thu Apr 20 00:31:40 2017 +0800
 2 files changed, 115 insertions(+)
 create mode 100644 init/bootchart_parse.cpp
=== Applying 657589/1 ===
From https://android.googlesource.com/platform/system/bt
 * branch                refs/changes/89/657589/1 -> FETCH_HEAD
[detached HEAD d94756709] vendor_libs: Allow btlinux service to run from vendor or system/vendor
 Author: Dmitry Shmidt <dimitrysh@google.com>
 Date: Thu Apr 5 10:35:37 2018 -0700
 1 file changed, 1 insertion(+), 1 deletion(-)
=== Cherry-picking 93ca85a1724806c30b0fbc04837a7e869ba1c165 ===
[detached HEAD 0273f7e8f57] Update PageTypeInfoParser to be less restrictive.
 Author: Kenneth Magic <kmagic@google.com>
 Date: Wed Jul 11 13:18:03 2018 -0700
 3 files changed, 6 insertions(+), 11 deletions(-)
=== Cherry-picking 34db0c778839e40656fc78905a7da5d626fc82a2 ===
**fatal: bad object 34db0c778839e40656fc78905a7da5d626fc82a2
34db0c778839e40656fc78905a7da5d626fc82a2 failed to apply, please fix**
HEAD is now at 1be2ab6 Update prebuilt Clang to build 4691093.

**Comment by vchong** [comment]
Thanks for reporting and sorry for the trouble. Should be ok now. Please `git pull` to the latest `optee_android_manifest` and try again.

**Comment by warraagal** [comment]
Thank you for the fix. The patches are successfully applied now.
