### ISSUE TITLE
System errors on android

### ISSUE THREAD

**Issue by beYunfei** [linaro-swg/optee_android_manifest#5]
Dear sir,

I use Hikey to setup AOSP+OPTEE, I met lots of system error on Android logcat, and also HDMI looks not working. Following are my steps:
1. To Build AOSP I simply follow your page "https://github.com/linaro-swg/optee_android_manifest", I modified build_kernel.sh at line 23 -> "cross=$(readlink -f "$cross")", or else it can not find the compiler on my  Ubuntu 14.04.1 LTS.
2. I built fip.bin according with optee_os [page](https://github.com/OP-TEE/optee_os/blob/master/README.md).
3. I copied fip.bin to AOSP/device/linaro/hikey/installer/ manually, and execute flash_all.sh

Following errors are found from my logcat:
1.  hundreds of warnings like "01-01 00:00:27.990  1771  1771 W Resources: Preloaded drawable resource #0x1080208 (android:drawable/btn_star_on_normal_holo_light) that varies with configuration!!"
2. 3 dozens `Permission denied(13)` erros like ```
   01-01 00:00:41.474  2184  2184 I PackageManager.DexOptimizer: Running dexopt (patchoat) on: /system/priv-app/SystemUI/SystemUI.apk pkg=com.android.systemui isa=arm64 vmSafeMode=false debuggable=false oatDir = null bootComplete=false useJit=false
   01-01 00:00:41.508  2311  2311 E cutils-trace: Error opening trace file: Permission denied (13)

```
3. Some errors:
```

01-01 00:00:49.321  2184  2184 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gatekeeper.password.key: open failed: ENOENT (No such file or directory)
01-01 00:00:49.322  2184  2184 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/password.key: open failed: ENOENT (No such file or directory)
01-01 00:00:49.322  2184  2184 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gatekeeper.pattern.key: open failed: ENOENT (No such file or directory)
01-01 00:00:49.323  2184  2184 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gatekeeper.gesture.key: open failed: ENOENT (No such file or directory)
01-01 00:00:49.324  2184  2184 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gesture.key: open failed: ENOENT (No such file or directory)

```
4. **System error**, in fact much more than bellow, I cannot enumates all:
```

01-01 00:00:49.730  2184  2201 W System.err: java.lang.IllegalArgumentException
01-01 00:00:49.731  2184  2201 W System.err:    at android.os.Process.setProcessGroup(Native Method)
01-01 00:00:49.731  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:18763)
01-01 00:00:49.731  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:19247)
01-01 00:00:49.731  2184  2201 W System.err:    at com.android.server.am.BroadcastQueue.processCurBroadcastLocked(BroadcastQueue.java:262)
01-01 00:00:49.731  2184  2201 W System.err:    at com.android.server.am.BroadcastQueue.sendPendingBroadcastsLocked(BroadcastQueue.java:297)
01-01 00:00:49.731  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.sendPendingBroadcastsLocked(ActivityManagerService.java:16259)
01-01 00:00:49.731  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6205)
01-01 00:00:49.731  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6246)
01-01 00:00:49.731  2184  2201 W System.err:    at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:507)
01-01 00:00:49.731  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2493)
01-01 00:00:49.731  2184  2201 W System.err:    at android.os.Binder.execTransact(Binder.java:453)
01-01 00:00:49.753  2415  2415 W System  : ClassLoader referenced unknown path: /system/priv-app/CalendarProvider/lib/arm64
01-01 00:00:49.788  2184  2201 I ActivityManager: Pre-boot of {com.android.providers.contacts/com.android.providers.contacts.ContactsUpgradeReceiver} for user 0
01-01 00:00:49.801  2184  2201 I ActivityManager: Start proc 2442:android.process.acore/u0a3 for broadcast com.android.providers.contacts/.ContactsUpgradeReceiver
01-01 00:00:49.837  2184  2201 I ActivityManager: Launching preboot mode app: ProcessRecord{a4063cc 2442:android.process.acore/u0a3}
01-01 00:00:49.838  2184  2201 W SchedPolicy: add_tid_to_cgroup failed to write '2442' (Permission denied); fd=29
01-01 00:00:49.838  2184  2201 W ActivityManager: Failed setting process group of 2442 to 0
01-01 00:00:49.838  2184  2201 W System.err: java.lang.IllegalArgumentException
01-01 00:00:49.838  2184  2201 W System.err:    at android.os.Process.setProcessGroup(Native Method)
01-01 00:00:49.838  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:18763)
01-01 00:00:49.839  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:19247)
01-01 00:00:49.839  2184  2201 W System.err:    at com.android.server.am.BroadcastQueue.processCurBroadcastLocked(BroadcastQueue.java:262)
01-01 00:00:49.839  2184  2201 W System.err:    at com.android.server.am.BroadcastQueue.sendPendingBroadcastsLocked(BroadcastQueue.java:297)
01-01 00:00:49.839  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.sendPendingBroadcastsLocked(ActivityManagerService.java:16259)
01-01 00:00:49.839  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6205)
01-01 00:00:49.839  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6246)
01-01 00:00:49.839  2184  2201 W System.err:    at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:507)
01-01 00:00:49.839  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2493)
01-01 00:00:49.839  2184  2201 W System.err:    at android.os.Binder.execTransact(Binder.java:453)
01-01 00:00:49.855  2442  2442 W System  : ClassLoader referenced unknown path: /system/priv-app/ContactsProvider/lib/arm64
01-01 00:00:50.753  2184  2440 W SchedPolicy: add_tid_to_cgroup failed to write '2460' (Permission denied); fd=29
01-01 00:00:50.754  2184  2440 W ActivityManager: Failed setting process group of 2460 to 0
01-01 00:00:50.754  2184  2440 W System.err: java.lang.IllegalArgumentException
01-01 00:00:50.754  2184  2440 W System.err:    at android.os.Process.setProcessGroup(Native Method)
01-01 00:00:50.754  2184  2440 W System.err:    at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:18763)
01-01 00:00:50.754  2184  2440 W System.err:    at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:19247)
01-01 00:00:50.754  2184  2440 W System.err:    at com.android.server.am.BroadcastQueue.processCurBroadcastLocked(BroadcastQueue.java:262)
01-01 00:00:50.755  2184  2440 W System.err:    at com.android.server.am.BroadcastQueue.sendPendingBroadcastsLocked(BroadcastQueue.java:297)
01-01 00:00:50.755  2184  2440 W System.err:    at com.android.server.am.ActivityManagerService.sendPendingBroadcastsLocked(ActivityManagerService.java:16259)
01-01 00:00:50.755  2184  2440 W System.err:    at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6205)
01-01 00:00:50.755  2184  2440 W System.err:    at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6246)
01-01 00:00:50.755  2184  2440 W System.err:    at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:507)
01-01 00:00:50.755  2184  2440 W System.err:    at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2493)
01-01 00:00:50.755  2184  2440 W System.err:    at android.os.Binder.execTransact(Binder.java:453)
01-01 00:00:50.774  2460  2460 W System  : ClassLoader referenced unknown path: /system/priv-app/ManagedProvisioning/lib/arm64
01-01 00:00:50.787  2184  2441 I ActivityManager: Pre-boot of {com.android.providers.media/com.android.providers.media.MediaUpgradeReceiver} for user 0
01-01 00:00:50.800  2184  2441 I ActivityManager: Start proc 2473:android.process.media/u0a5 for broadcast com.android.providers.media/.MediaUpgradeReceiver
01-01 00:00:50.827  2184  2201 I ActivityManager: Launching preboot mode app: ProcessRecord{4f5f0b8 2473:android.process.media/u0a5}
01-01 00:00:50.838  2184  2201 W SchedPolicy: add_tid_to_cgroup failed to write '2473' (Permission denied); fd=29
01-01 00:00:50.838  2184  2201 W ActivityManager: Failed setting process group of 2473 to 0
01-01 00:00:50.838  2184  2201 W System.err: java.lang.IllegalArgumentException
01-01 00:00:50.838  2184  2201 W System.err:    at android.os.Process.setProcessGroup(Native Method)
01-01 00:00:50.838  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:18763)
01-01 00:00:50.839  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:19247)
01-01 00:00:50.839  2184  2201 W System.err:    at com.android.server.am.BroadcastQueue.processCurBroadcastLocked(BroadcastQueue.java:262)
01-01 00:00:50.839  2184  2201 W System.err:    at com.android.server.am.BroadcastQueue.sendPendingBroadcastsLocked(BroadcastQueue.java:297)
01-01 00:00:50.839  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.sendPendingBroadcastsLocked(ActivityManagerService.java:16259)
01-01 00:00:50.839  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6205)
01-01 00:00:50.839  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6246)
01-01 00:00:50.839  2184  2201 W System.err:    at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:507)
01-01 00:00:50.839  2184  2201 W System.err:    at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2493)
01-01 00:00:50.839  2184  2201 W System.err:    at android.os.Binder.execTransact(Binder.java:453)
01-01 00:00:50.856  2473  2473 W System  : ClassLoader referenced unknown path: /system/priv-app/MediaProvider/lib/arm64

01-01 00:00:51.371  2525  2525 W System  : ClassLoader referenced unknown path: /system/priv-app/SystemUI/lib/arm64
01-01 00:00:51.393  2184  2184 I Telecom : PhoneAccountRegistrar: SimCallManager queried, returning: null
01-01 00:00:51.394  2525  2525 V SystemUIService: Starting SystemUI services.
01-01 00:00:51.402  2556  2556 W System  : ClassLoader referenced unknown path: /system/priv-app/ContactsProvider/lib/arm64
01-01 00:00:51.440  2556  2556 W System  : ClassLoader referenced unknown path: /system/app/UserDictionaryProvider/lib/arm64
01-01 00:00:51.490  2184  2184 W SchedPolicy: add_tid_to_cgroup failed to write '2556' (Permission denied); fd=29
01-01 00:00:51.490  2184  2184 W ActivityManager: Failed setting process group of 2556 to 0
01-01 00:00:51.490  2184  2184 W System.err: java.lang.IllegalArgumentException
01-01 00:00:51.490  2184  2184 W System.err:    at android.os.Process.setProcessGroup(Native Method)
01-01 00:00:51.490  2184  2184 W System.err:    at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:18763)
01-01 00:00:51.490  2184  2184 W System.err:    at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:19247)
01-01 00:00:51.491  2184  2184 W System.err:    at com.android.server.am.ActivityManagerService.removeContentProvider(ActivityManagerService.java:9866)
01-01 00:00:51.491  2184  2184 W System.err:    at android.app.ActivityThread.completeRemoveProvider(ActivityThread.java:5087)
01-01 00:00:51.491  2184  2184 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475)
01-01 00:00:51.491  2184  2184 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
01-01 00:00:51.491  2184  2184 W System.err:    at android.os.Looper.loop(Looper.java:148)
01-01 00:00:51.491  2184  2184 W System.err:    at com.android.server.SystemServer.run(SystemServer.java:292)
01-01 00:00:51.491  2184  2184 W System.err:    at com.android.server.SystemServer.main(SystemServer.java:169)
01-01 00:00:51.491  2184  2184 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
01-01 00:00:51.491  2184  2184 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
01-01 00:00:51.491  2184  2184 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
01-01 00:00:51.630  2515  2515 I art     : System.exit called, status: 0
01-01 00:00:51.630  2515  2515 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.

```
```

**Comment by d3zd3z** [comment]
I guess first question, are you able to build a plan AOSP (without optee)? Instructions are at: https://source.android.com/source/devices.html . I recommend getting this to work before trying to build a tree that contains optee.

**Comment by beYunfei** [comment]
Hi @d3zd3z ,
Sorry for replying late, I met some internet connection problem last couple days, the answer is yes, I can compile a plan AOSP. I have tried this before, I will do another test and get back to you later. Thanks!
