### ISSUE TITLE
HiKey620 can't boot after flashing branch lcr-ref-hikey

### ISSUE THREAD

**Issue by bryan370210** [linaro-swg/optee_android_manifest#52]
hi, I build  and flash lcr-ref-hikey  into hikey620 successful. but the board can not boot after power on

**Comment by vchong** [comment]
@bryan370210 seems like a kernel issue, not op-tee. Working on a workaround while waiting for the fix by the right people. In the meantime, you can:
```
wget http://snapshots.linaro.org/android/android-hikey-optee-p/122/boot.img.xz
unxz boot.img.xz
sudo fastboot flash boot boot.img
```

Btw, thanks for closing old issues!

**Comment by bryan370210** [comment]
@vchong  it works ,thank you.

**Comment by vchong** [comment]
@bryan370210 it didn't work initially but now it does? What happened in between? Can we close this then?
