### ISSUE TITLE
errors in building branch lcr-ref-hikey

### ISSUE THREAD

**Issue by bryan370210** [linaro-swg/optee_android_manifest#53]
I used sync-p.sh and build-p.sh  in building branch lcr-ref-hikey for hikey 620, and get these errors

build.py...
 : error 7000: Failed to execute command
        make tbuild [/media/wen/e4502d1f-7070-4268-8e06-73585c204394/optee/1-lc-ref-hikey-2019.01.24/optee_android_manifest/device/linaro/bootloader/edk2/Build/HiKey/RELEASE_GCC49/AARCH64/MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenanceManagerUiLib]

build.py...
 : error F002: Failed to build module
        /media/wen/e4502d1f-7070-4268-8e06-73585c204394/optee/1-lc-ref-hikey-2019.01.24/optee_android_manifest/device/linaro/bootloader/edk2/MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenanceManagerUiLib.inf [AARCH64, GCC49, RELEASE]

- Failed -
Build end time: 19:42:11, Jan.24 2019
Build total time: 00:00:27

------------------------------------------------------------
                                CircuitCo HiKey RELEASE fail
------------------------------------------------------------
pass    0
fail    1
Makefile:30: recipe for target '/media/wen/e4502d1f-7070-4268-8e06-73585c204394/optee/1-lc-ref-hikey-2019.01.24/optee_android_manifest/out/dist/fip.bin' failed
make: *** [/media/wen/e4502d1f-7070-4268-8e06-73585c204394/optee/1-lc-ref-hikey-2019.01.24/optee_android_manifest/out/dist/fip.bin] Error 1
make: Leaving directory '/media/wen/e4502d1f-7070-4268-8e06-73585c204394/optee/1-lc-ref-hikey-2019.01.24/optee_android_manifest/device/linaro/hikey/bootloader'
ninja: build stopped: subcommand failed.
19:42:11 ninja failed with: exit status 1
Build done!
Please make sure there are no errors before flashing!

**Comment by tesmnorth** [comment]
> I used sync-p.sh and build-o.sh in building branch lcr-ref-hikey for hikey 620, and get these errors

I think, you must use `build-p.sh` after `sync-p.sh`

**Comment by bryan370210** [comment]
@tesmnorth typo error，I used build-p.sh
