### ISSUE TITLE
error when flash hikey960

### ISSUE THREAD

**Issue by bryan370210** [linaro-swg/optee_android_manifest#57]
I get these errors when flash the hikey 960, then  flash-all.sh will be wating untill using ctrl+c, the branch is optee_kmgk_3.4.0

# ./flash-all.sh  /dev/ttyUSB0 
android out dir:.
flashing recovery images.. please wait ~10 seconds
Config name: ./config
Port name: /dev/ttyUSB0
0: Image: device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img Downalod Address: 0x20000
1: Image: device/linaro/hikey/installer/hikey960/hisi-sec_uce_boot.img Downalod Address: 0x6a908000
2: Image: device/linaro/hikey/installer/hikey960/recovery.bin Downalod Address: 0x1ac00000
Serial port open successfully!
Start downloading device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img@0x20000...
Error when open file device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img
./flash-all.sh: line 58: 31381 segment error               sudo "${INSTALLER_DIR}"/hikey_idt -c "${INSTALLER_DIR}"/config -p "${DEVICE_PORT}"
set a unique serial num

**Comment by vchong** [comment]
Does `device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img` exist?

**Comment by bryan370210** [comment]
I forgot the path "device/linaro/hikey/installer/hikey960" ,thank you vchong
