### ISSUE TITLE
The screen issue on hikey960

### ISSUE THREAD

**Issue by tulipper** [linaro-swg/optee_android_manifest#59]
Hello guys!
I can build and flash the optee+aosp on my hikey960  absolutely correct except the screen issue. 
The screen is always turn black and display disorder!
My touch screen is powered by a DC charger sepatately not by using the usb, and uses usb for touch control, I can ensure there is no matter with my touch screen, because I have check it by plug in the computer and it works well.
Now I a little believe there is a system matter because I found the one who met a very similar question [https://discuss.96boards.org/t/hikey960-screen-problem/7136](url)

> > The image you have above seems like you’re missing the patch here:
> https://android-review.googlesource.com/c/kernel/hikey-linaro/+/889696/
> 
> Can you double check the source you built and confirm it has that change?
> 
> I double check source I built. There is no change in kirin_drm_overlay_utils.c. I changed the file according to link you sent. Finally, my screen is working. :slight_smile: . Before your last post, I think, kirin_drm_overlay_utils.c wasn’t changed in optee_android_manifest. Thanks

In the link above, he finally uses a patch and change some files to solve the problem. May be I can also solve it by doing this, but I am quite confused with the patch link, and have no idea on what to do. could someone give any advices? thanks a lot. 
![1292113527](https://user-images.githubusercontent.com/37870574/58232937-67ecf300-7d6d-11e9-944b-568deb861448.jpg) 
It looks like this when it display disorder.

**Comment by jockebech** [comment]
No clue, but one thing is sure and that it has nothing to do with OP-TEE, we're not touching anything related to that. So I guess it's better to seek advise regarding this on the 96Boards forum.

**Comment by tulipper** [comment]
Thanks for your advice!

> but one thing is sure and that it has nothing to do with OP-TEE,

Yes, I absolutely believe that. 
Another thing is that the console is always outputing these message:
```
[18085.521844] hisi_ddr_devfreq ddr_devfreq: set down threshold:685000000
[18087.363289] hisi_ddr_devfreq ddr_devfreq: ddr bandwdith request: 0 / 28472
[18087.370333] hisi_ddr_devfreq ddr_devfreq: set down threshold:400000000
[20420.163483] hisi_ddr_devfreq ddr_devfreq: ddr bandwdith request: 0 / 28472
[20420.171382] hisi_ddr_devfreq ddr_devfreq: set down threshold:685000000
[20421.179252] hisi_ddr_devfreq ddr_devfreq: ddr bandwdith request: 0 / 28472
[20421.186285] hisi_ddr_devfreq ddr_devfreq: set down threshold:400000000
[20422.503342] hisi_ddr_devfreq ddr_devfreq: ddr bandwdith request: 0 / 28472
[20422.510384] hisi_ddr_devfreq ddr_devfreq: set down threshold:685000000
[20425.059246] hisi_ddr_devfreq ddr_devfreq: ddr bandwdith request: 0 / 28472
[20425.066213] hisi_ddr_devfreq ddr_devfreq: set down threshold:400000000
[20425.252671] hisi_ddr_devfreq ddr_devfreq: ddr bandwdith request: 0 / 28472
[20425.260908] hisi_ddr_devfreq ddr_devfreq: set down threshold:685000000
[20426.340586] hisi_ddr_devfreq ddr_devfreq: ddr bandwdith request: 0 / 28472
[20426.347545] hisi_ddr_devfreq ddr_devfreq: set down threshold:400000000
[20555.232004] hisi_ddr_devfreq ddr_devfreq: ddr bandwdith request: 0 / 28472
[20555.239127] hisi_ddr_devfreq ddr_devfreq: set down threshold:685000000
[20557.973026] hisi_ddr_devfreq ddr_devfreq: ddr bandwdith request: 0 / 28472
[20557.979995] hisi_ddr_devfreq ddr_devfreq: set down threshold:400000000
[20558.300273] hisi_ddr_devfreq ddr_devfreq: ddr bandwdith request: 0 / 28472
[20558.308135] hisi_ddr_devfreq ddr_devfreq: set down threshold:685000000
[20559.376393] hisi_ddr_devfreq ddr_devfreq: ddr bandwdith request: 0 / 28472
[20559.383341] hisi_ddr_devfreq ddr_devfreq: set down threshold:400000000
```

So what is the meaning of these message and is it normal? Is it related to the screen display problems?
Thanks for your kind reply!

**Comment by jockebech** [comment]
> So what is the meaning of these message and is it normal? Is it related to the screen display problems?

Don't know, since I don't own any Hikey960, I only own the old HiKey (620) and that error message isn't seen when running that device.

**Comment by tulipper** [comment]
Thank you! 
I want to change the refresh rate and this change seems should be done in the kernal command line. What commandline should I add and to which files. I want to try it, any advices are appreciated.Thank you .

**Comment by jockebech** [comment]
Again, I'm referring to the 96Boards forum, [there seems to be many threads touching this](https://discuss.96boards.org/search?q=kernel%20commandline).

**Comment by vchong** [comment]
> I am quite confused with the patch link, and have no idea on what to do. could someone give any advices?

```
cd kernel/linaro/hisilicon-4.14
git fetch "https://android.googlesource.com/kernel/hikey-linaro" refs/changes/96/889696/2 && git cherry-pick FETCH_HEAD
# make sure no error, else do NOT continue
cd -
# rerun build*.sh script and reflash boot.img
```
> I want to change the refresh rate and this change seems should be done in the kernal command line. What commandline should I add and to which files

```
cd device/linaro/hikey/hikey960
# edit BoardConfig.mk by adding a line like below
# BOARD_KERNEL_CMDLINE += video=HDMI-A-1:800x480@60
# You can also try other rates, like @70, 75, 80, 85
cd -
# rerun build*.sh script and reflash boot.img
```

**Comment by tulipper** [comment]
Thank you @vchong  Thanks @jbech-linaro !

```
> cd device/linaro/hikey/hikey960
> # edit BoardConfig.mk by adding a line like below
> # BOARD_KERNEL_CMDLINE += video=HDMI-A-1:800x480@60
> # You can also try other rates, like @70, 75, 80, 85
> cd -
> # rerun build*.sh script and reflash boot.img
```

Do this change and rebuild and reflash boot.img, but it doesn't change the resolution at all, it looks like the same as before. I guess the rate is not  changed either. 
And I found some material in [https://elinux.org/Beagleboard:BeagleBoneBlack_HDMI](here):

> You can set the default resolution on the initial power up for the splash screen by adding the following to the uENV.txt file where you can use any resolution you choose:
> 
> video=HDMI-A-1:640x480@60
> 
> HOWEVER, this will only set the resolution on the first stage of the boot process for the splash screen, when the BEAGELBONE LOGO is displayed at the beginning. After reading the EDID, the board will use the EDID as the resolution.
> This will tell you if the monitor, cable, and the board are all functioning from a HW perspective.


Could this be the reason why the resolution is not changed?

BTW . Is linux kernel in boot.img?

**Comment by vchong** [comment]
> Do this change and rebuild and reflash boot.img, but it doesn't change the resolution at all, it looks like the same as before. I guess the rate is not changed either.

What does your BoardConfig.mk file look like?

> Could this be the reason why the resolution is not changed?

Sorry but this is for the BBB so we don't know if it works the same way or differently.

> BTW . Is linux kernel in boot.img?

Yes.

Finally, this isn't really an OP-TEE related issue so as mentioned above, best to get help from the forum. Also, this might give you more info: https://bugs.96boards.org/show_bug.cgi?id=827

**Comment by tulipper** [comment]
Thank you @vchong @jbech-linaro . I replace the file

>  optee_android_manifest/kernel/linaro/hisilicon-4.14/drivers/gpu/drm/hisilicon/kirin960/dw_drm_dsi.c

 with [https://android.googlesource.com/kernel/hikey-linaro/+/refs/heads/android-hikey-linaro-4.14/drivers/gpu/drm/hisilicon/kirin960/dw_drm_dsi.c#1055](url)
then rebuild the whold aosp and flash boot.img. Now the monitor seems work fine. I referenced to the bug commit. I guess there is a bug in this kermel version, expect can fix this in the future.

> Finally, this isn't really an OP-TEE related issue so as mentioned above, best to get help from the >forum. Also, this might give you more info: https://bugs.96boards.org/show_bug.cgi?id=827

**Comment by vchong** [comment]
Thanks for the update! Glad you got it to work.

> I guess there is a bug in this kermel version, expect can fix this in the future.

Yes, probably when the manifest was snapshot, the kernel didn't have the patch applied yet, but the hikey* boards have always had issues with HDMI, and patches kept getting changed/updated. It's a good thing Adam in https://bugs.96boards.org/show_bug.cgi?id=827 made extensive analyses of the issue and seemed to have found a good workaround. We should direct all screen/HDMI related issues to that url from now on.
