### ISSUE TITLE
Compile error for first android build

### ISSUE THREAD

**Issue by yingkailiang** [linaro-swg/optee_android_manifest#6]
Hi, 

I follow the description list in optee_android_manifest repo. I am at the stage to build the android+OPTEE for the first time. Following the error message I get when I build android source code. 

`duct/hikey/obj/ETC/sepolicy_intermediates/sepolicy.tmp out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy )"
device/linaro/hikey/sepolicy/file.te:2:ERROR 'duplicate declaration of type/attribute' at token ';' on line 15544:
type configfs, fs_type;
# line 1 "device/linaro/hikey/sepolicy/file.te"

checkpolicy:  error(s) encountered while parsing configuration
ninja: build stopped: subcommand failed.
make: **\* [ninja_wrapper] Error 1`

Based on the error message, seems the device/linaro/hikey/sepolicy/file.te file contains syntax error. Any suggestion how to fix it. 

Thanks in advance.

**Comment by d3zd3z** [comment]
It looks like this was added in `system/sepolicy` in commit:

```
commit c15090b315cc32d4bb55b5ff79b71b4383e1a793
Author: Daniel Rosenberg <drosen@google.com>
Date:   Tue Mar 1 16:13:50 2016 -0800

    sepolicy: Add policy for sdcardfs and configfs

    Change-Id: I4c318efba76e61b6ab0be9491c352f281b1c2bff
    Bug: 19160983
```

I'm not sure of the exact correct fix, but you could probably just remove that line from the file.te, since it is indeed now redundant with the file.te in `system/sepolicy`.

**Comment by radheshkrishnan** [comment]
When I removed that line, I am getting following error. 

```
[  0% 10/37395] build out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy
FAILED: /bin/bash -c "(out/host/linux-x86/bin/checkpolicy -M -c 29 -o out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.tmp out/target/product/hikey/obj/ETC/sepolicy_intermediates/policy.conf > /dev/null ) && (out/host/linux-x86/bin/checkpolicy -M -c 29 -o out/target/product/hikey/obj/ETC/sepolicy_intermediates//sepolicy.dontaudit out/target/product/hikey/obj/ETC/sepolicy_intermediates/policy.conf.dontaudit > /dev/null ) && (out/host/linux-x86/bin/sepolicy-analyze out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.tmp permissive > out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ]; then       echo \"==========\" 1>&2;       echo \"ERROR: permissive domains not allowed in user builds\" 1>&2;     echo \"List of invalid domains:\" 1>&2;         cat out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains 1>&2;        exit 1;         fi ) && (mv out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.tmp out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy )"
device/linaro/hikey/sepolicy/genfs_contexts:3:ERROR 'duplicate entry for genfs entry (configfs, /)' at token '' on line 15658:
genfscon configfs / u:object_r:configfs:s0


```

So I removed "genfscon configfs / u:object_r:configfs:s0" this line too.  I hope it compiles now.

**Comment by radheshkrishnan** [comment]
It was all working before I updated the repo. Now I compiled removing following
```

type configfs, fs_type;
genfscon configfs / u:object_r:configfs:s0

```
I flashed all images to Hikey board. However, I am not able to load tee_supplicant now. 

#ls /dev/tee*
ls: /dev/tee*: No such file or directory

Is these problems related? I followed the instructions exactly explained here and  It had worked before. Could someone please help?

**Comment by yingkailiang** [comment]
@radheshkrishnan  By removing both sepolicy files, the compilation succeed. Although, I am not quite sure whether it will cause any problems when I run the system.

**Comment by d3zd3z** [comment]
Probably not. If anything, you are probably running userdebug, where selinux isn't enforcing anyway. But I think these policies have just been included in the AOSP tree and don't need to be included in the device-specific files.
