### ISSUE TITLE
Problem about sync command

### ISSUE THREAD

**Issue by tesmnorth** [linaro-swg/optee_android_manifest#62]
`./sync-p-hikey960.sh` command causes following error.

```
tee: logs/sync-p.log: No such file or directory
No local mirrors
./sync.sh: line 50: syntax error near unexpected token `)'
```
Solution: (if anybody don't want to wait fixing this problem) Add ';;' before line 50

**Comment by vchong** [comment]
Fixed. Thanks for the report!
