### ISSUE TITLE
Synch Problem in google-breakpad

### ISSUE THREAD

**Issue by tesmnorth** [linaro-swg/optee_android_manifest#63]
While synch, problem is occured like this:
```
error: Exited sync due to fetch errors
xternal/google-breakpad
```

**Comment by vchong** [comment]
There's not enough info to debug. Please include the log files in `logs/`.

**Comment by tesmnorth** [comment]
`logs` folder is empty. While synching, there is a problem. More logs from terminal:
```
From https://android.googlesource.com/platform/external/icu
   6151fee76..2bdd3a630  master             -> aosp/master
   7e268f52a..032182b92  sdk-release        -> aosp/sdk-release
   09f445017..ee4fbcbb0  simpleperf-release -> aosp/simpleperf-release

error: Exited sync due to fetch errors
xternal/google-breakpad
Fetching project platform/external/python/numpy
Fetching project platform/external/ims
Fetching project platform/external/gptfdisk
Fetching project platform/external/jline
Fetching project platform/external/python/dill
Fetching project platform/system/tools/aidl
Fetching project platform/external/owasp/sanitizer
Fetching project platform/frameworks/opt/inputconnectioncommon
Fetching project platform/packages/apps/SafetyRegulatoryInfo


```

**Comment by vchong** [comment]
Sorry but don't see anything obvious.
It's a bit weird that the `e` is missing from `xternal/google-breakpad`. I don't suppose you changed any xml files, right?
If you start again from scratch, do you still get this error? If so, please list the steps and we'll try to reproduce here.

**Comment by vchong** [comment]
Please see if https://github.com/linaro-swg/optee_android_manifest/issues/64 is related.

**Comment by tesmnorth** [comment]
> I don't suppose you changed any xml files, right?

No, I didnt change anything.

> If you start again from scratch, do you still get this error? 

Yes. 

> If so, please list the steps and we'll try to reproduce here.

`git clone https://github.com/linaro-swg/optee_android_manifest` 
`cd optee_android_manifest`
`./sync-p-hikey960.sh`

> Please see if #64 is related.

Yes. I think, it is totally related with #64

**Comment by vchong** [comment]
Fixed on master. Please close if issue is resolved. Thanks.

**Comment by tesmnorth** [comment]
It's done @vchong. Thank you. Now I will build it.
