### ISSUE TITLE
prebuilts clang is missing clang-r349610 which causes build failure

### ISSUE THREAD

**Issue by ammarsalman94** [linaro-swg/optee_android_manifest#66]
The sync command attempts to download clang-r349610 from the google repository but it is not there anymore as the link (provided by google) does not work anymore. Here is the link: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/clang-r349610/

Unfortunately, this breaks the build process since there are missing files during check. The error is: 

> /bin/bash: line 0: cd: prebuilts/clang/host/linux-x86/clang-r349610/bin: No such file or directory
> /bin/bash: line 0: cd: prebuilts/clang/host/linux-x86/clang-r349610/bin: No such file or directory

I have checked and verified, it is not there anymore. 

Any ideas?

**Comment by vchong** [comment]
What commands/script are you using?

**Comment by ammarsalman94** [comment]
@vchong I am using build-p.sh (got Hikey 620 8gb)

**Comment by ammarsalman94** [comment]
So I tried a few things, I tinkered around with **_abc/hikey-optee-p_** file and tried changing clang-r349610 to clang-4691093 which is listed as the recommended clang to build 9.0.0_R34 (as indicated by the config file). However, that did not work and the build failed in compiling source code files. So I figured it was not the correct prebuild. 

There, I wanted to get clang-r349610 and I was finally able to find it, but it was not listed under Android 9 at all, instead it was under 10 (link: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/tags/android-10.0.0_r28/clang-r349610/ ) 

I downloaded and extracted it to: **_{manifest folder}/prebuilts/clang/host/linux-x86/clang-r349610/_**

The build was complete and no errors occurred.
