### ISSUE TITLE
Build failure in optee_os

### ISSUE THREAD

**Issue by warraagal** [linaro-swg/optee_android_manifest#67]
generator.c failed to compile
I have posted the relevant section of the logs below.

<pre>
FAILED: out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/dba51a17-0563-11e7-93b1-6fa7b0071a51.ta 
/bin/bash -c "(make -j4 -C /media/DATA1/rounaka/optee_aosp/device/linaro/kmgk/keymaster/ta O=\$(/media/DATA1/rounaka/optee_aosp/prebuilts/build-tools/linux-x86/bin/ckati --realpath out/target/product/hikey960 2> /dev/null)/optee/ta/device_linaro_kmgk_keymaster_ta 		TA_DEV_KIT_DIR=/media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/arm-plat-hikey/export-ta_arm64 		CROSS_COMPILE64=\"/media/DATA1/rounaka/optee_aosp/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-\" CROSS_COMPILE32=\"/media/DATA1/rounaka/optee_aosp/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-\" ) && (echo \"Finished building TA for device/linaro/kmgk/keymaster/ta out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/dba51a17-0563-11e7-93b1-6fa7b0071a51.ta...\" )"
make: Entering directory '/media/DATA1/rounaka/optee_aosp/device/linaro/kmgk/keymaster/ta'
  CC      /media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/keystore_ta.o
  CC      /media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/parsel.o
  CC      /media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/operations.o
  CC      /media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/tables.o
  CC      /media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/master_crypto.o
  CC      /media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/paddings.o
  CC      /media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/parameters.o
  CC      /media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/auth.o
  CC      /media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/generator.o
  CC      /media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/asn1.o
generator.c: In function 'TA_create_operation':
generator.c:767:12: error: 'TEE_ALG_RSASSA_PKCS1_PSS_MGF1_MD5' undeclared (first use in this function)
     algo = TEE_ALG_RSASSA_PKCS1_PSS_MGF1_MD5;
            ^
generator.c:767:12: note: each undeclared identifier is reported only once for each function it appears in
generator.c:799:12: error: 'TEE_ALG_RSAES_PKCS1_OAEP_MGF1_MD5' undeclared (first use in this function)
     algo = TEE_ALG_RSAES_PKCS1_OAEP_MGF1_MD5;
            ^
/media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/arm-plat-hikey/export-ta_arm64/mk/compile.mk:147: recipe for target '/media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/generator.o' failed
make: *** [/media/DATA1/rounaka/optee_aosp/out/target/product/hikey960/optee/ta/device_linaro_kmgk_keymaster_ta/generator.o] Error 1
</pre>

**Comment by warraagal** [comment]
I should have mentioned that I am trying to build for Hikey960.
Used the following command for syncing.
<pre>
./sync.sh -v p -d -t hikey960 -bm pinned-manifest_hikey960_v9r34_v3.6.1_20190903.xml --ref /media/rounaka/AOSPRepoMirror -j 3
</pre>

For building
<pre>
./build.sh -v p -t hikey960 -j 3
</pre>

**Comment by vchong** [comment]
The builds don't seem to work now due some of the external repos being moved to a different url and we're currently stalled in development.

In any case, it looks like the optee_os repo isn't synced or patched properly. You can try below and then rebuild.

```
cd /media/DATA1/rounaka/optee_aosp/optee/optee_os
git fetch https://github.com/OP-TEE/optee_os 2f6dffbd324d3a7a15da684df5b250461d109cb5 && git checkout FETCH_HEAD
curl https://github.com/liuyq/optee_os/commit/f61316c1f92b64dcd7e861726a5812bb1d5cce74.patch | git am
git fetch https://github.com/vchong/optee_os kmgk_pta_rebase && git cherry-pick 8d8cca7c0a1d8194731c7b002f5e12d0fc0d12d6^..8e0f58f1ef3a99ceb9876cc4e468d78b470e8923
cd /media/DATA1/rounaka/optee_aosp/out/target/product/hikey960
rm -f optee
cd /media/DATA1/rounaka/optee_aosp
./build.sh -v p -t hikey960 -j 3
```

**Comment by warraagal** [comment]
> The builds don't seem to work now due some of the external repos being moved to a different url and we're currently stalled in development.

Yes, while syncing, there was a problem in applying patches because of changed URLs. But I fixed the errors by editing the patch file P-RLCR-PATCHSET. After that, the sync did not have any more errors. But the build still failed.
I will try the steps you have posted.

**Comment by warraagal** [comment]
Sync errors have been fixed by PR https://github.com/linaro-swg/optee_android_manifest/pull/68
I am unable to reproduce the build errors after a fresh sync.
So closing this issue.
