### ISSUE TITLE
Sync Problem (pinned-manifest_hikey960_v9r34_v3.8.2_20200501.xml)

### ISSUE THREAD

**Issue by uikang** [linaro-swg/optee_android_manifest#69]
13 line in archive/pinned-manifest_hikey960_v9r34_v3.8.2_20200501.xml

project groups="device,hikey960" name="96boards-hikey/OpenPlatformPkg.git" path="optee/OpenPlatformPkg" remote="github-optee" revision="76bbfcc0bfa4184ed5991fe89c8d7039f8ffeb46" upstream="testing/hikey960_v1.3.4"

revision="76bbfcc0bfa4184ed5991fe89c8d7039f8ffeb46" dose not exist in testing/hikey960_v1.3.4 branch.
The latest revision is "245344ea5421ba126e1eb76484d00b590a4a78f7"

https://github.com/96boards-hikey/OpenPlatformPkg/commit/245344ea5421ba126e1eb76484d00b590a4a78f7

**Comment by vchong** [comment]
@uikang Thanks for the report! Will push a fix.

**Comment by uikang** [comment]
Can you know when it will be fixed?

**Comment by vchong** [comment]
@uikang Sorry for the delay. Just pushed the fix. Please try again with `master` branch or `3.8.3` tag.

**Comment by vchong** [comment]
@uikang Please note that we still can't boot to the home screen with this release due to issues not related to OP-TEE. Cli is ok. For details please see https://github.com/OP-TEE/build/issues/418.

**Comment by vchong** [comment]
@uikang Please see https://github.com/OP-TEE/build/issues/418#issuecomment-653767005 if this still applies.
