### ISSUE TITLE
Undeclared variables in tee_fs.h

### ISSUE THREAD

**Issue by radheshkrishnan** [linaro-swg/optee_android_manifest#7]
Hi all,

I am getting new compilation errors after a repo sync.

`external/optee_client/tee-supplicant/src/tee_fs.h:174:12: error: use of undeclared identifier 'R_OK'
                flags |= R_OK;
                         ^
external/optee_client/tee-supplicant/src/tee_fs.h:177:12: error: use of undeclared identifier 'W_OK'
                flags |= W_OK;
                         ^
external/optee_client/tee-supplicant/src/tee_fs.h:180:12: error: use of undeclared identifier 'F_OK'
                flags |= F_OK;
`

How do we relove it?

Thank you,
Radhesh

**Comment by fogeater** [comment]
same error

**Comment by fogeater** [comment]
seems external/optee_client/tee-supplicant/src/tee_fs.h  donot include <unistd.h>.
add the head file, and it wroks to me.
