### ISSUE TITLE
v3.8.3 on Hikey960-4G board : TEE OS Panic at core_mmu_lpae.c 

### ISSUE THREAD

**Issue by sunzc** [linaro-swg/optee_android_manifest#71]
I had experience with v3.4.2, and it works fine on my hikey960-4GB board. 
Now I am checking out v3.8.3 and building it successfully for hikey960-4GB board on Ubuntu16.04.

As I'm aware of the issue with OP-TEE OS 3.8.0.(default for optee_android_manifest-v3.8.3)
Before I build, the only changes I made for hikey960-4GB board are:
change-1. optee_os/core/arch/arm/plat-hikey/conf.mk
change the default DRAM SIZE from 3 GB to 4GB
```
CFG_DRAM_SIZE_GB ?= 4 
```

change-2. add support for 4GB/6GB by adding the following lines
in optee_os/core/arch/arm/plat-hikey/conf.mk
```
# Hikey960 4G/6G versions have physical addresses above 4G range
ifneq (,$(filter 4 6,$(CFG_DRAM_SIZE_GB)))
$(call force,CFG_CORE_ARM64_PA_BITS,36)
endif
```

After building, when I run flash-all.sh(jumper setting: 1-2,3-4, set; 5-6, unset), I find the board get stuck. Here is the flash log:
```
=== android out dir:./device/linaro/hikey/installer/hikey960/../../../../..//out/target/product/hikey960
android out imgdir:./device/linaro/hikey/installer/hikey960/../../../../..//out/target/product/hikey960
flashing recovery images.. please wait ~10 seconds
Config name: ./device/linaro/hikey/installer/hikey960/config
Port name: /dev/ttyUSB1
0: Image: device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img Downalod Address: 0x20000
1: Image: device/linaro/hikey/installer/hikey960/hisi-sec_uce_boot.img Downalod Address: 0x6a908000
2: Image: device/linaro/hikey/installer/hikey960/recovery.bin Downalod Address: 0x1ac00000
Serial port open successfully!
Start downloading device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img@0x20000...
file total size 99584
downlaod address 0x20000
Finish downloading
Start downloading device/linaro/hikey/installer/hikey960/hisi-sec_uce_boot.img@0x6a908000...
file total size 23680
downlaod address 0x6a908000
Finish downloading
Start downloading device/linaro/hikey/installer/hikey960/recovery.bin@0x1ac00000...
file total size 1179648
downlaod address 0x1ac00000
Finish downloading
sleep 10
skip setting a unique serial number for now
flashing all other images
=== Checking partition table version...
fastboot erase reserved
< waiting for any device >
```

After I checked the TEE Log from uart, I find TEE OS panic at 
```
E/TC:0 0 Panic at core/arch/arm/mm/core_mmu_lpae.c:366 <check_nsec_ddr_max_pa>
```
The detailed TEE log is:
```
iomcu_subsys_init
boot_c0 PROFILE 4
slave0 irq0:0x00000004
slave1 irq0:0x00000004
NOTICE:  BL2: v2.3():v2.3-14-g455a6f3
NOTICE:  BL2: Built : 11:36:29, Jun  2 2020
NOTICE:  ufs: H**** device must set VS_DebugSaveConfigTime 0x10
NOTICE:  BL2: Booting BL31
NOTICE:  BL31: v2.3():v2.3-14-g455a6f3
NOTICE:  BL31: Built : 11:36:29, Jun  2 2020
D/TC:0 0 add_phys_mem:581 TEE_SHMEM_START type NSEC_SHM 0x3ee00000 size 0x00200000
D/TC:0 0 add_phys_mem:581 TA_RAM_START type TA_RAM 0x3f200000 size 0x00e00000
D/TC:0 0 add_phys_mem:581 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x3f064000 size 0x0019c000
D/TC:0 0 add_phys_mem:581 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x3f000000 size 0x00064000
D/TC:0 0 add_phys_mem:581 ROUNDDOWN(0xFFF32000, CORE_MMU_PGDIR_SIZE) type IO_NSEC 0xffe00000 size 0x00200000
D/TC:0 0 verify_special_mem_areas:525 SDP memory [3e800000 3ec00000]
D/TC:0 0 verify_special_mem_areas:525 NSEC DDR memory [200000000 220000000]
D/TC:0 0 verify_special_mem_areas:525 NSEC DDR memory [40000000 e0000000]
D/TC:0 0 verify_special_mem_areas:525 NSEC DDR memory [0 3e000000]
D/TC:0 0 add_va_space:620 type RES_VASPACE size 0x00a00000
D/TC:0 0 add_va_space:620 type SHM_VASPACE size 0x02000000
D/TC:0 0 dump_mmap_table:732 type IO_NSEC      va 0x3ae00000..0x3affffff pa 0xffe00000..0xffffffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type TA_RAM       va 0x3b000000..0x3bdfffff pa 0x3f200000..0x3fffffff size 0x00e00000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type NSEC_SHM     va 0x3c000000..0x3c1fffff pa 0x3ee00000..0x3effffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type SHM_VASPACE  va 0x3c200000..0x3e1fffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type RES_VASPACE  va 0x3e400000..0x3edfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type TEE_RAM_RX   va 0x3f000000..0x3f063fff pa 0x3f000000..0x3f063fff size 0x00064000 (smallpg)
D/TC:0 0 dump_mmap_table:732 type TEE_RAM_RW   va 0x3f064000..0x3f1fffff pa 0x3f064000..0x3f1fffff size 0x0019c000 (smallpg)
E/TC:0 0 Panic at core/arch/arm/mm/core_mmu_lpae.c:366 <check_nsec_ddr_max_pa>
E/TC:0 0 TEE load address @ 0x3f000000
E/TC:0 0 Call stack:
E/TC:0 0  0x000000003f00b538

```
I also tried the same thing without change-2, the result is the same.
I thought the change-2 would solve the above problem, but it doesn't. 

Any idea on how to get v3.8.3 work on hikey960-4G board ? Even not a fully working version(like no UI, as long as Android boots) is ok for me.

Thanks!

**Comment by jenswikl** [comment]
It looks like `CFG_CORE_ARM64_PA_BITS` hasn't been set properly.

**Comment by vchong** [comment]
```
=== Checking partition table version...
fastboot erase reserved
< waiting for any device >
```

Is this all the log? If so, then nothing is flashed at all. You can try flashing manually by going to `device/linaro/hikey/installer/hikey960/` and then:

```
sudo ./hikey_idt -c config -p /dev/ttyUSB0
# wait for the fastboot prompt to appear on the board/console
fastboot flash ptable prm_ptable.img
fastboot flash xloader hisi-sec_xloader.img
fastboot flash fastboot l-loader.bin
fastboot flash fip fip.bin
fastboot flash nvme hisi-nvme.img
fastboot flash boot boot.img
fastboot flash cache cache.img
fastboot flash system system.img
fastboot flash userdata userdata.img
fastboot flash vendor vendor.img
```

**Note** that you need modify the `config` file if u flash manually as below:
```
hisi-sec_usb_xloader.img 0x00020000
hisi-sec_uce_boot.img 0x6A908000
recovery.bin 0x1AC00000
```

You also need to use a different number if you serial is not connected to ` /dev/ttyUSB0`.

**Comment by sunzc** [comment]
> It looks like `CFG_CORE_ARM64_PA_BITS` hasn't been set properly.

I thought it was the `CFG_CORE_ARM64_PA_BITS` problem so I add the following code to handle it.
```
# Hikey960 4G/6G versions have physical addresses above 4G range
ifneq (,$(filter 4 6,$(CFG_DRAM_SIZE_GB)))
$(call force,CFG_CORE_ARM64_PA_BITS,36)
endif
```

Now I find it might be the board problem. The board I'm using can't enter into fastboot mode even with `1-2, 5-6 set, 3-4 unset`. And the TEE panic log is shown.  I tried the exactly same flash process on another board, and it successfully enter fastboot mode.  I can flash the board now. But it get stuck on Android Booting, only a `android` logo is shown on the screen.

**Comment by sunzc** [comment]
> ```
> === Checking partition table version...
> fastboot erase reserved
> < waiting for any device >
> ```
> 
> Is this all the log? If so, then nothing is flashed at all. You can try flashing manually by going to `device/linaro/hikey/installer/hikey960/` and then:
> 
> ```
> sudo ./hikey_idt -c config -p /dev/ttyUSB0
> # wait for the fastboot prompt to appear on the board/console
> fastboot flash ptable prm_ptable.img
> fastboot flash xloader hisi-sec_xloader.img
> fastboot flash fastboot l-loader.bin
> fastboot flash fip fip.bin
> fastboot flash nvme hisi-nvme.img
> fastboot flash boot boot.img
> fastboot flash cache cache.img
> fastboot flash system system.img
> fastboot flash userdata userdata.img
> fastboot flash vendor vendor.img
> ```
> 
> **Note** that you need modify the `config` file if u flash manually as below:
> 
> ```
> hisi-sec_usb_xloader.img 0x00020000
> hisi-sec_uce_boot.img 0x6A908000
> recovery.bin 0x1AC00000
> ```
> 
> You also need to use a different number if you serial is not connected to ` /dev/ttyUSB0`.

I find the board I'm using can not enter fastboot mode. I tried another board and  successfully flashed the board.  Now it seems for v3.8.3, Android can not fully boot, it get stuck at `android` logo. But I can use adb shell to access the board. 

I'm searching for a AOSP+OPTEE version that optee support dynamic memory sharing and AOSP can support install and run android applications.  I tried v3.4.2, the AOSP works fine but OP-TEE OS does not support Dynamic Memory Sharing. Could you suggest a optee_android_manifest version that might support both ?

Thank you!
