### ISSUE TITLE
OPTEE + Android 9.0 on i.MX8 series

### ISSUE THREAD

**Issue by sarju32** [linaro-swg/optee_android_manifest#72]
Dear @vchong 

I have seen activities related to porting OPTEE in AOSP on HiKey platforms.

There is a requirement on porting OPTEE on the custom reference based on NXP's i.MX8M

Have certain interface and Android Application requirement to leverage TEE services.

1. Need to port OPTEE along with Android 9.0 to i.MX8M 
2. Need to port drivers Debug UART, Audio, WiFI, USB, I2C, SPI to OPTEE OS
3. A VoIP based Call application need to be developed.
4. Finger print Sensor through USB interface need to be developed.

In above this, the Custom Call application also need to leverage TEE services.

There maybe complexity to achieve this. But I would like to know your comments.

Plus I have seen OPTEE + AOSP running on HiKey platform. Is that the only reference we have to make use. Any idea you have of porting OPTEE + Android on NXPs platform.

Let me know.

Thanks in advance.

**Comment by vchong** [comment]
> There is a requirement on porting OPTEE on the custom reference based on NXP's i.MX8M

Already done. See [1].

>    Need to port OPTEE along with Android 9.0 to i.MX8M

This is also already done. See [2] and [3]. But I don't know how you'd be able to get the tarball required for the build. Please contact your NXP rep.

> Need to port drivers Debug UART, Audio, WiFI, USB, I2C, SPI to OPTEE OS

Uart is done during the initial platform port [4]. i2c driver is there [5]. The rest you'll have to port yourself.

>    A VoIP based Call application need to be developed.
>    Finger print Sensor through USB interface need to be developed.

These you'll have to implement yourself as well.

> Plus I have seen OPTEE + AOSP running on HiKey platform. Is that the only reference we have to make use.

Unfortunately yes. The hikey is our only reference implementation atm.

[1] https://optee.readthedocs.io/en/latest/general/platforms.html#platforms-supported
[2] https://community.nxp.com/thread/501070
[3] https://www.nxp.com/document/guide/get-started-with-the-mcimx8m-evk:GS-MCIMX8M-EVK
[4] https://github.com/OP-TEE/optee_os/blob/master/core/drivers/imx_lpuart.c
[5] https://github.com/OP-TEE/optee_os/blob/master/core/drivers/imx_i2c.c
