### ISSUE TITLE
How big the `.repo` will be?

### ISSUE THREAD

**Issue by WindowsXp-Beta** [linaro-swg/optee_android_manifest#73]
I've been running `./sync-p-hikey960.sh` for about one day and the `.repo` in `optee_android_manifest` has reached 155GB and it's still executing the `repo sync j2...`.
New to OPTEE and aosp. Should it be like this? How big the `.repo` will eventually be?

**Comment by vchong** [comment]
Mine is about 80GB. Not sure if `.repo` will reduce in size when the sync is done. Is your linux machine a virtual one in a windows host? Perhaps you can try from a different machine to see if it makes a difference.

**Comment by WindowsXp-Beta** [comment]
Yes, I use a virtual Ubuntu20.04.1 in my Mac host. I can't build it in a VM?

**Comment by vchong** [comment]
You can. It'll just be slower. It's already taking quite a long time on the host system itself unless you're using a powerful machine.
