### ISSUE TITLE
rerun `sync-p-hikey960.sh`

### ISSUE THREAD

**Issue by WindowsXp-Beta** [linaro-swg/optee_android_manifest#74]
I was running `sync-p-hikey960.sh` when an unknown error occurred so I have to type ctrl+c and rerun it.
Can the script know where it stopped last time and continue from here?

I know `repo sync` can but the size of `.repo` has reached 217GB(before rerunning, it is 165GB and stays for about 30mins which makes me think it has finished downloading aosp). (I've asked about the size in #73)
Also, I don't quite understand what `--force-sync is used which means you might lose your work so save often, save frequent, and save accordingly, especially before running sync-p.sh again!` means in the [Doc](https://optee.readthedocs.io/en/latest/building/aosp/aosp.html).  How to **save** my work? Can I just rerun the script?

Btw, I am using `3.8.3` and Ubuntu 16.04.

**Comment by vchong** [comment]
> Can the script know where it stopped last time and continue from here?

Yes. The script uses `repo sync` in the end as well.

> I know repo sync can but the size of .repo has reached 217GB(before rerunning, it is 165GB and stays for about 30mins which makes me think it has finished downloading aosp). (I've asked about the size in #73)

If the sync script has finished, you should see something like below.
```
Sync done!
Please make sure there are no errors before building!
```
If not, run `sync-p-hikey960.sh -j 1` and see where it fails. It's not finished if it seems stuck or has not returned to the prompt.

> Also, I don't quite understand what --force-sync is used which means you might lose your work so save often, save frequent, and save accordingly, especially before running sync-p.sh again! means in the Doc. How to save my work? Can I just rerun the script?

You only need to worry about this if you make changes to the code in any of the repositories. If you rerun the script without saving your changes, then your changes will be erased. One way of 'saving' your work is to `git push` your changes to your own branch on github.

> Btw, I am using 3.8.3 and Ubuntu 16.04.

3.8.3 can only boot to the command line but doesn't show the home screen [1]. Please try 3.12.0 or 3.13.0 instead. Also, Ubuntu 16.04 is quite old and hasn't really been tested so can't tell what problems you might face. If possible, try 18.04 or 20.04.

[1] https://github.com/linaro-swg/optee_android_manifest/issues/70
