### ISSUE TITLE
How to build OP-TEE with an older version of Android (Android 6)?

### ISSUE THREAD

**Issue by radheshkrishnan** [linaro-swg/optee_android_manifest#8]
Hi all,

When I check out this branch it get latest version of AOSP? 
Is it possible to get an older version of AOSP + OP-TEE?

Thank you,
Radhesh

**Comment by vchong** [comment]
Please see if http://www.96boards.org/forums/topic/compile-android-hikey-linaro-4-1-android-6-0 can maybe help.
