### ISSUE TITLE
Build Problem with:type hci_attach_exec is not defined

### ISSUE THREAD

**Issue by yijiabin** [linaro-swg/optee_android_manifest#9]
Dear Sir:
      When I follow the decsription list in optee_android_manifest repo, I meet the same error in [https://github.com/linaro-swg/optee_android_manifest/issues/6](url), After I delete the two files: **_device/linaro/hikey/sepolicy/file.te_** and **_device/linaro/hikey/sepolicy/genfs_contexts_**, the build continued.But an  error occurd:  **_libsepol.context_from_record: type hci_attach_exec is not defined._**

    The whole infomation is 
build **_out/target/product/hikey/obj/ETC/nonplat_file_contexts_intermediates/nonplat_file_contexts_**
FAILED: out/target/product/hikey/obj/ETC/nonplat_file_contexts_intermediates/nonplat_file_contexts
/bin/bash -c "(m4 -s     **_device/linaro/hikey/sepolicy/file_contexts_**  out/target/product/hikey/obj/ETC/sectxfile_nl_intermediates/sectxfile_nl > out/target/product/hikey/obj/ETC/nonplat_file_contexts_intermediates/nonplat_file_contexts.tmp ) && (out/host/linux-x86/bin/checkfc out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy out/target/product/hikey/obj/ETC/nonplat_file_contexts_intermediates/nonplat_file_contexts.tmp ) && (out/host/linux-x86/bin/fc_sort out/target/product/hikey/obj/ETC/nonplat_file_contexts_intermediates/nonplat_file_contexts.tmp out/target/product/hikey/obj/ETC/nonplat_file_contexts_intermediates/nonplat_file_contexts )"
libsepol.context_from_record: **_type hci_attach_exec is not defined_**
libsepol.context_from_record: could not create context structure
out/target/product/hikey/obj/ETC/nonplat_file_contexts_intermediates/nonplat_file_contexts.tmp: **_line 7 has invalid context u:object_r:hci_attach_exec:s0_**
libsepol.context_from_record: type hci_attach_exec is not defined
libsepol.context_from_record: could not create context structure
out/target/product/hikey/obj/ETC/nonplat_file_contexts_intermediates/nonplat_file_contexts.tmp: line 7 has invalid context u:object_r:hci_attach_exec:s0
Error: could not load context file from out/target/product/hikey/obj/ETC/nonplat_file_contexts_intermediates/nonplat_file_contexts.tmp
ninja: build stopped: subcommand failed.

I have searched file **_device/linaro/hikey/sepolicy/file_contexts_**, **_line 7 is /system/bin/uim        u:object_r:hci_attach_exec:s0_**.

Could someone tell me how to fix the error? Can you @d3zd3z give me a hand?

**Comment by yijiabin** [comment]
I have fix the error by moving a **_hci_attch.te_** from android sourcecode(AOSP) without OPTEE.
**_type hci_attach_exec, exec_type, file_type;_** is in **_aosp/device/linaro/hikey/sepolicy/hci_attch.te_** file.

**Comment by RajashekarPP** [comment]
@https://github.com/yijiabin

Can u help me in understanding the above issue faced by you.
I am unable to fix the same issue.
I am not getting the above explanation given by you.

**Comment by vchong** [comment]
@RajashekarPP he means try adding a line that says `type hci_attach_exec, exec_type, file_type;` in the `device/linaro/hikey/sepolicy/hci_attch.te` file.

**Comment by Mikdadali** [comment]
please help me to solve this

https://del.dog/lonacyluna

**Comment by vchong** [comment]
@Mikdadali `libsepol.context_from_record: type vendor_camera_prop is not defined`. Try adding `type vendor_camera_prop, property_type` in `device/<vendor>/violet/sepolicy/property.te` to see if that helps. If not, not sure how else to help you either since this isn't really OP-TEE related. Your platform doesn't even seem to be HiKey related.

**Comment by Mikdadali** [comment]
@vchong thanks its working

**Comment by vchong** [comment]
@Mikdadali Great. You're welcome.
